#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_CloneRoutingRuleSet")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class @__CloneRoutingRuleSetRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference RoutingRuleSetIdToClone
		{
			get
			{
				if (this.Parameters.Contains("RoutingRuleSetIdToClone"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["RoutingRuleSetIdToClone"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["RoutingRuleSetIdToClone"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference RoutingRuleSetIdToOverwrite
		{
			get
			{
				if (this.Parameters.Contains("RoutingRuleSetIdToOverwrite"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["RoutingRuleSetIdToOverwrite"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["RoutingRuleSetIdToOverwrite"] = value;
			}
		}
		
		public string Options
		{
			get
			{
				if (this.Parameters.Contains("Options"))
				{
					return ((string)(this.Parameters["Options"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Options"] = value;
			}
		}
		
		public @__CloneRoutingRuleSetRequest()
		{
			this.RequestName = "_CloneRoutingRuleSet";
			this.RoutingRuleSetIdToClone = default(Microsoft.Xrm.Sdk.EntityReference);
			this.Options = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("_CloneRoutingRuleSet")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class @__CloneRoutingRuleSetResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public @__CloneRoutingRuleSetResponse()
		{
		}
		
		public string RoutingRuleSetCopyRecordId
		{
			get
			{
				if (this.Results.Contains("RoutingRuleSetCopyRecordId"))
				{
					return ((string)(this.Results["RoutingRuleSetCopyRecordId"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
