#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_EvaluateSearchRequest")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class @__EvaluateSearchRequestRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string ServiceAppointmentId
		{
			get
			{
				if (this.Parameters.Contains("ServiceAppointmentId"))
				{
					return ((string)(this.Parameters["ServiceAppointmentId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ServiceAppointmentId"] = value;
			}
		}
		
		public string ServiceId
		{
			get
			{
				if (this.Parameters.Contains("ServiceId"))
				{
					return ((string)(this.Parameters["ServiceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ServiceId"] = value;
			}
		}
		
		public int DateOptionSet
		{
			get
			{
				if (this.Parameters.Contains("DateOptionSet"))
				{
					return ((int)(this.Parameters["DateOptionSet"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["DateOptionSet"] = value;
			}
		}
		
		public int TimeOptionSet
		{
			get
			{
				if (this.Parameters.Contains("TimeOptionSet"))
				{
					return ((int)(this.Parameters["TimeOptionSet"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["TimeOptionSet"] = value;
			}
		}
		
		public string DayList
		{
			get
			{
				if (this.Parameters.Contains("DayList"))
				{
					return ((string)(this.Parameters["DayList"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["DayList"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection RequiredResources
		{
			get
			{
				if (this.Parameters.Contains("RequiredResources"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["RequiredResources"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["RequiredResources"] = value;
			}
		}
		
		public string SearchWindowStart
		{
			get
			{
				if (this.Parameters.Contains("SearchWindowStart"))
				{
					return ((string)(this.Parameters["SearchWindowStart"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SearchWindowStart"] = value;
			}
		}
		
		public string SearchWindowEnd
		{
			get
			{
				if (this.Parameters.Contains("SearchWindowEnd"))
				{
					return ((string)(this.Parameters["SearchWindowEnd"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SearchWindowEnd"] = value;
			}
		}
		
		public int SearchRecurrenceStart
		{
			get
			{
				if (this.Parameters.Contains("SearchRecurrenceStart"))
				{
					return ((int)(this.Parameters["SearchRecurrenceStart"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["SearchRecurrenceStart"] = value;
			}
		}
		
		public int TimeRangeEnd
		{
			get
			{
				if (this.Parameters.Contains("TimeRangeEnd"))
				{
					return ((int)(this.Parameters["TimeRangeEnd"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["TimeRangeEnd"] = value;
			}
		}
		
		public int Duration
		{
			get
			{
				if (this.Parameters.Contains("Duration"))
				{
					return ((int)(this.Parameters["Duration"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["Duration"] = value;
			}
		}
		
		public int Direction
		{
			get
			{
				if (this.Parameters.Contains("Direction"))
				{
					return ((int)(this.Parameters["Direction"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["Direction"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection Sites
		{
			get
			{
				if (this.Parameters.Contains("Sites"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["Sites"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["Sites"] = value;
			}
		}
		
		public int NumberOfResults
		{
			get
			{
				if (this.Parameters.Contains("NumberOfResults"))
				{
					return ((int)(this.Parameters["NumberOfResults"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["NumberOfResults"] = value;
			}
		}
		
		public string @__SearchWindowStart
		{
			get
			{
				if (this.Parameters.Contains("_SearchWindowStart"))
				{
					return ((string)(this.Parameters["_SearchWindowStart"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["_SearchWindowStart"] = value;
			}
		}
		
		public string @__SearchWindowEnd
		{
			get
			{
				if (this.Parameters.Contains("_SearchWindowEnd"))
				{
					return ((string)(this.Parameters["_SearchWindowEnd"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["_SearchWindowEnd"] = value;
			}
		}
		
		public @__EvaluateSearchRequestRequest()
		{
			this.RequestName = "_EvaluateSearchRequest";
			this.ServiceId = default(string);
			this.Duration = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("_EvaluateSearchRequest")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class @__EvaluateSearchRequestResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public @__EvaluateSearchRequestResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection AvailableSlots
		{
			get
			{
				if (this.Results.Contains("AvailableSlots"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["AvailableSlots"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
		}
	}
}
#pragma warning restore CS1591
