#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_ResourcesRemoveUpdateAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class @__ResourcesRemoveUpdateActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string ResourcesToBeRemoved
		{
			get
			{
				if (this.Parameters.Contains("ResourcesToBeRemoved"))
				{
					return ((string)(this.Parameters["ResourcesToBeRemoved"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ResourcesToBeRemoved"] = value;
			}
		}
		
		public string ResourceGroupId
		{
			get
			{
				if (this.Parameters.Contains("ResourceGroupId"))
				{
					return ((string)(this.Parameters["ResourceGroupId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ResourceGroupId"] = value;
			}
		}
		
		public @__ResourcesRemoveUpdateActionRequest()
		{
			this.RequestName = "_ResourcesRemoveUpdateAction";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("_ResourcesRemoveUpdateAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class @__ResourcesRemoveUpdateActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public @__ResourcesRemoveUpdateActionResponse()
		{
		}
	}
}
#pragma warning restore CS1591
