#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("_SaveServiceTreeData")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class @__SaveServiceTreeDataRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string RootNodeId
		{
			get
			{
				if (this.Parameters.Contains("RootNodeId"))
				{
					return ((string)(this.Parameters["RootNodeId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RootNodeId"] = value;
			}
		}
		
		public string ResourceRuleList
		{
			get
			{
				if (this.Parameters.Contains("ResourceRuleList"))
				{
					return ((string)(this.Parameters["ResourceRuleList"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ResourceRuleList"] = value;
			}
		}
		
		public @__SaveServiceTreeDataRequest()
		{
			this.RequestName = "_SaveServiceTreeData";
			this.RootNodeId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011//")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("_SaveServiceTreeData")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class @__SaveServiceTreeDataResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public @__SaveServiceTreeDataResponse()
		{
		}
		
		public string Error
		{
			get
			{
				if (this.Results.Contains("Error"))
				{
					return ((string)(this.Results["Error"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string UpdatedRootNode
		{
			get
			{
				if (this.Results.Contains("UpdatedRootNode"))
				{
					return ((string)(this.Results["UpdatedRootNode"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
