#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("CCaaS_SendAHTEvents")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CCaaS_SendAHTEventsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string ApiVersion
		{
			get
			{
				if (this.Parameters.Contains("ApiVersion"))
				{
					return ((string)(this.Parameters["ApiVersion"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ApiVersion"] = value;
			}
		}
		
		public string Payload
		{
			get
			{
				if (this.Parameters.Contains("Payload"))
				{
					return ((string)(this.Parameters["Payload"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Payload"] = value;
			}
		}
		
		public CCaaS_SendAHTEventsRequest()
		{
			this.RequestName = "CCaaS_SendAHTEvents";
			this.ApiVersion = default(string);
			this.Payload = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("CCaaS_SendAHTEvents")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CCaaS_SendAHTEventsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public CCaaS_SendAHTEventsResponse()
		{
		}
		
		public string Message
		{
			get
			{
				if (this.Results.Contains("Message"))
				{
					return ((string)(this.Results["Message"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string Status
		{
			get
			{
				if (this.Results.Contains("Status"))
				{
					return ((string)(this.Results["Status"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
