#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("CCaaS_InitiateAgentTransfer")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CCaaS_InitiateAgentTransferRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public System.Guid QueueId
		{
			get
			{
				if (this.Parameters.Contains("QueueId"))
				{
					return ((System.Guid)(this.Parameters["QueueId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["QueueId"] = value;
			}
		}
		
		public string ApiVersion
		{
			get
			{
				if (this.Parameters.Contains("ApiVersion"))
				{
					return ((string)(this.Parameters["ApiVersion"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ApiVersion"] = value;
			}
		}
		
		public System.Guid AgentId
		{
			get
			{
				if (this.Parameters.Contains("AgentId"))
				{
					return ((System.Guid)(this.Parameters["AgentId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["AgentId"] = value;
			}
		}
		
		public CCaaS_InitiateAgentTransferRequest()
		{
			this.RequestName = "CCaaS_InitiateAgentTransfer";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
			this.ApiVersion = default(string);
			this.AgentId = default(System.Guid);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("CCaaS_InitiateAgentTransfer")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CCaaS_InitiateAgentTransferResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public CCaaS_InitiateAgentTransferResponse()
		{
		}
	}
}
#pragma warning restore CS1591
