#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("CCaaS_InitiateAgentTransferExternal")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CCaaS_InitiateAgentTransferExternalRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public string AgentName
		{
			get
			{
				if (this.Parameters.Contains("AgentName"))
				{
					return ((string)(this.Parameters["AgentName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["AgentName"] = value;
			}
		}
		
		public string ExternalParticipantChannel
		{
			get
			{
				if (this.Parameters.Contains("ExternalParticipantChannel"))
				{
					return ((string)(this.Parameters["ExternalParticipantChannel"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ExternalParticipantChannel"] = value;
			}
		}
		
		public string ApiVersion
		{
			get
			{
				if (this.Parameters.Contains("ApiVersion"))
				{
					return ((string)(this.Parameters["ApiVersion"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ApiVersion"] = value;
			}
		}
		
		public string ExternalReferenceId
		{
			get
			{
				if (this.Parameters.Contains("ExternalReferenceId"))
				{
					return ((string)(this.Parameters["ExternalReferenceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ExternalReferenceId"] = value;
			}
		}
		
		public string ExternalParticipantChannelType
		{
			get
			{
				if (this.Parameters.Contains("ExternalParticipantChannelType"))
				{
					return ((string)(this.Parameters["ExternalParticipantChannelType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ExternalParticipantChannelType"] = value;
			}
		}
		
		public string ExternalReferenceType
		{
			get
			{
				if (this.Parameters.Contains("ExternalReferenceType"))
				{
					return ((string)(this.Parameters["ExternalReferenceType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ExternalReferenceType"] = value;
			}
		}
		
		public CCaaS_InitiateAgentTransferExternalRequest()
		{
			this.RequestName = "CCaaS_InitiateAgentTransferExternal";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
			this.ExternalParticipantChannel = default(string);
			this.ApiVersion = default(string);
			this.ExternalParticipantChannelType = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("CCaaS_InitiateAgentTransferExternal")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CCaaS_InitiateAgentTransferExternalResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public CCaaS_InitiateAgentTransferExternalResponse()
		{
		}
	}
}
#pragma warning restore CS1591
