#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("CCaaS_GetAvailabilityForConversation")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CCaaS_GetAvailabilityForConversationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string ApiVersion
		{
			get
			{
				if (this.Parameters.Contains("ApiVersion"))
				{
					return ((string)(this.Parameters["ApiVersion"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ApiVersion"] = value;
			}
		}
		
		public string CustomContextItems
		{
			get
			{
				if (this.Parameters.Contains("CustomContextItems"))
				{
					return ((string)(this.Parameters["CustomContextItems"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CustomContextItems"] = value;
			}
		}
		
		public System.Guid ConversationId
		{
			get
			{
				if (this.Parameters.Contains("ConversationId"))
				{
					return ((System.Guid)(this.Parameters["ConversationId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["ConversationId"] = value;
			}
		}
		
		public CCaaS_GetAvailabilityForConversationRequest()
		{
			this.RequestName = "CCaaS_GetAvailabilityForConversation";
			this.ApiVersion = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("CCaaS_GetAvailabilityForConversation")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CCaaS_GetAvailabilityForConversationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public CCaaS_GetAvailabilityForConversationResponse()
		{
		}
		
		public double AverageWaitTime
		{
			get
			{
				if (this.Results.Contains("AverageWaitTime"))
				{
					return ((double)(this.Results["AverageWaitTime"]));
				}
				else
				{
					return default(double);
				}
			}
		}
		
		public System.DateTime EndTimeOfNextOperatingHour
		{
			get
			{
				if (this.Results.Contains("EndTimeOfNextOperatingHour"))
				{
					return ((System.DateTime)(this.Results["EndTimeOfNextOperatingHour"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
		}
		
		public bool IsAgentAvailable
		{
			get
			{
				if (this.Results.Contains("IsAgentAvailable"))
				{
					return ((bool)(this.Results["IsAgentAvailable"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
		
		public bool IsQueueAvailable
		{
			get
			{
				if (this.Results.Contains("IsQueueAvailable"))
				{
					return ((bool)(this.Results["IsQueueAvailable"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
		
		public System.DateTime NextTransitionTime
		{
			get
			{
				if (this.Results.Contains("NextTransitionTime"))
				{
					return ((System.DateTime)(this.Results["NextTransitionTime"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
		}
		
		public int PositionInQueue
		{
			get
			{
				if (this.Results.Contains("PositionInQueue"))
				{
					return ((int)(this.Results["PositionInQueue"]));
				}
				else
				{
					return default(int);
				}
			}
		}
		
		public string QueueId
		{
			get
			{
				if (this.Results.Contains("QueueId"))
				{
					return ((string)(this.Results["QueueId"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public System.DateTime StartTimeOfNextOperatingHour
		{
			get
			{
				if (this.Results.Contains("StartTimeOfNextOperatingHour"))
				{
					return ((System.DateTime)(this.Results["StartTimeOfNextOperatingHour"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
		}
	}
}
#pragma warning restore CS1591
