#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("CCaaS_CloseConversation")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CCaaS_CloseConversationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public System.Guid LiveworkitemId
		{
			get
			{
				if (this.Parameters.Contains("LiveworkitemId"))
				{
					return ((System.Guid)(this.Parameters["LiveworkitemId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["LiveworkitemId"] = value;
			}
		}
		
		public System.Guid AgentId
		{
			get
			{
				if (this.Parameters.Contains("AgentId"))
				{
					return ((System.Guid)(this.Parameters["AgentId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["AgentId"] = value;
			}
		}
		
		public string ActivityStatusCode
		{
			get
			{
				if (this.Parameters.Contains("ActivityStatusCode"))
				{
					return ((string)(this.Parameters["ActivityStatusCode"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ActivityStatusCode"] = value;
			}
		}
		
		public CCaaS_CloseConversationRequest()
		{
			this.RequestName = "CCaaS_CloseConversation";
			this.LiveworkitemId = default(System.Guid);
			this.AgentId = default(System.Guid);
			this.ActivityStatusCode = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("CCaaS_CloseConversation")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CCaaS_CloseConversationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public CCaaS_CloseConversationResponse()
		{
		}
	}
}
#pragma warning restore CS1591
