#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("CCaaS_ForceCloseConversation")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CCaaS_ForceCloseConversationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public string ApiVersion
		{
			get
			{
				if (this.Parameters.Contains("ApiVersion"))
				{
					return ((string)(this.Parameters["ApiVersion"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ApiVersion"] = value;
			}
		}
		
		public CCaaS_ForceCloseConversationRequest()
		{
			this.RequestName = "CCaaS_ForceCloseConversation";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
			this.ApiVersion = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("CCaaS_ForceCloseConversation")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CCaaS_ForceCloseConversationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public CCaaS_ForceCloseConversationResponse()
		{
		}
	}
}
#pragma warning restore CS1591
