#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("CCaaS_SetPresence")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CCaaS_SetPresenceRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string ApiVersion
		{
			get
			{
				if (this.Parameters.Contains("ApiVersion"))
				{
					return ((string)(this.Parameters["ApiVersion"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ApiVersion"] = value;
			}
		}
		
		public System.Guid PresenceId
		{
			get
			{
				if (this.Parameters.Contains("PresenceId"))
				{
					return ((System.Guid)(this.Parameters["PresenceId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["PresenceId"] = value;
			}
		}
		
		public CCaaS_SetPresenceRequest()
		{
			this.RequestName = "CCaaS_SetPresence";
			this.ApiVersion = default(string);
			this.PresenceId = default(System.Guid);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("CCaaS_SetPresence")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class CCaaS_SetPresenceResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public CCaaS_SetPresenceResponse()
		{
		}
	}
}
#pragma warning restore CS1591
