#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("DeleteAutomatedPlugin")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class DeleteAutomatedPluginRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string pluginid
		{
			get
			{
				if (this.Parameters.Contains("pluginid"))
				{
					return ((string)(this.Parameters["pluginid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["pluginid"] = value;
			}
		}
		
		public DeleteAutomatedPluginRequest()
		{
			this.RequestName = "DeleteAutomatedPlugin";
			this.pluginid = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("DeleteAutomatedPlugin")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class DeleteAutomatedPluginResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public DeleteAutomatedPluginResponse()
		{
		}
	}
}
#pragma warning restore CS1591
