#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ExecuteManagePowerBiReportsAndMetadata")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class ExecuteManagePowerBiReportsAndMetadataRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public ExecuteManagePowerBiReportsAndMetadataRequest()
		{
			this.RequestName = "ExecuteManagePowerBiReportsAndMetadata";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ExecuteManagePowerBiReportsAndMetadata")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class ExecuteManagePowerBiReportsAndMetadataResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ExecuteManagePowerBiReportsAndMetadataResponse()
		{
		}
	}
}
#pragma warning restore CS1591
