#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("ExecuteFxExpression")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class ExecuteFxExpressionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string context
		{
			get
			{
				if (this.Parameters.Contains("context"))
				{
					return ((string)(this.Parameters["context"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["context"] = value;
			}
		}
		
		public string entitylogicalname
		{
			get
			{
				if (this.Parameters.Contains("entitylogicalname"))
				{
					return ((string)(this.Parameters["entitylogicalname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entitylogicalname"] = value;
			}
		}
		
		public string expression
		{
			get
			{
				if (this.Parameters.Contains("expression"))
				{
					return ((string)(this.Parameters["expression"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["expression"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity outputparameters
		{
			get
			{
				if (this.Parameters.Contains("outputparameters"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["outputparameters"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Parameters["outputparameters"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity inputparameters
		{
			get
			{
				if (this.Parameters.Contains("inputparameters"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["inputparameters"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Parameters["inputparameters"] = value;
			}
		}
		
		public ExecuteFxExpressionRequest()
		{
			this.RequestName = "ExecuteFxExpression";
			this.expression = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("ExecuteFxExpression")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class ExecuteFxExpressionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public ExecuteFxExpressionResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity @out
		{
			get
			{
				if (this.Results.Contains("out"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["out"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
		}
	}
}
#pragma warning restore CS1591
