#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("fileClone")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class fileCloneRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string botId
		{
			get
			{
				if (this.Parameters.Contains("botId"))
				{
					return ((string)(this.Parameters["botId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["botId"] = value;
			}
		}
		
		public string mimeType
		{
			get
			{
				if (this.Parameters.Contains("mimeType"))
				{
					return ((string)(this.Parameters["mimeType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["mimeType"] = value;
			}
		}
		
		public string targetBotComponentId
		{
			get
			{
				if (this.Parameters.Contains("targetBotComponentId"))
				{
					return ((string)(this.Parameters["targetBotComponentId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["targetBotComponentId"] = value;
			}
		}
		
		public string fileName
		{
			get
			{
				if (this.Parameters.Contains("fileName"))
				{
					return ((string)(this.Parameters["fileName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["fileName"] = value;
			}
		}
		
		public string sourceBotComponentId
		{
			get
			{
				if (this.Parameters.Contains("sourceBotComponentId"))
				{
					return ((string)(this.Parameters["sourceBotComponentId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["sourceBotComponentId"] = value;
			}
		}
		
		public fileCloneRequest()
		{
			this.RequestName = "fileClone";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("fileClone")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class fileCloneResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public fileCloneResponse()
		{
		}
		
		public string fileCloneResponse
		{
			get
			{
				if (this.Results.Contains("fileCloneResponse"))
				{
					return ((string)(this.Results["fileCloneResponse"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
