#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("InstantiateTemplateGeneric")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class InstantiateTemplateGenericRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public System.Guid ObjectId
		{
			get
			{
				if (this.Parameters.Contains("ObjectId"))
				{
					return ((System.Guid)(this.Parameters["ObjectId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["ObjectId"] = value;
			}
		}
		
		public System.Guid TemplateId
		{
			get
			{
				if (this.Parameters.Contains("TemplateId"))
				{
					return ((System.Guid)(this.Parameters["TemplateId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["TemplateId"] = value;
			}
		}
		
		public string ObjectType
		{
			get
			{
				if (this.Parameters.Contains("ObjectType"))
				{
					return ((string)(this.Parameters["ObjectType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ObjectType"] = value;
			}
		}
		
		public string EntityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("EntityLogicalName"))
				{
					return ((string)(this.Parameters["EntityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityLogicalName"] = value;
			}
		}
		
		public InstantiateTemplateGenericRequest()
		{
			this.RequestName = "InstantiateTemplateGeneric";
			this.ObjectId = default(System.Guid);
			this.TemplateId = default(System.Guid);
			this.ObjectType = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/crm/2011/Contracts")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("InstantiateTemplateGeneric")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class InstantiateTemplateGenericResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public InstantiateTemplateGenericResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection EntityCollection
		{
			get
			{
				if (this.Results.Contains("EntityCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["EntityCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
		}
	}
}
#pragma warning restore CS1591
