#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_getSalesSequenceExperimentVersion")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_getSalesSequenceExperimentVersionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_customerId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_customerId"))
				{
					return ((string)(this.Parameters["msdyn_customerId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_customerId"] = value;
			}
		}
		
		public int msdyn_versionATraffic
		{
			get
			{
				if (this.Parameters.Contains("msdyn_versionATraffic"))
				{
					return ((int)(this.Parameters["msdyn_versionATraffic"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["msdyn_versionATraffic"] = value;
			}
		}
		
		public string msdyn_experimentKey
		{
			get
			{
				if (this.Parameters.Contains("msdyn_experimentKey"))
				{
					return ((string)(this.Parameters["msdyn_experimentKey"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_experimentKey"] = value;
			}
		}
		
		public string msdyn_experimentVersionRecordId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_experimentVersionRecordId"))
				{
					return ((string)(this.Parameters["msdyn_experimentVersionRecordId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_experimentVersionRecordId"] = value;
			}
		}
		
		public msdyn_getSalesSequenceExperimentVersionRequest()
		{
			this.RequestName = "msdyn_getSalesSequenceExperimentVersion";
			this.msdyn_customerId = default(string);
			this.msdyn_versionATraffic = default(int);
			this.msdyn_experimentKey = default(string);
			this.msdyn_experimentVersionRecordId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_getSalesSequenceExperimentVersion")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_getSalesSequenceExperimentVersionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_getSalesSequenceExperimentVersionResponse()
		{
		}
		
		public string msdyn_experimentVersionResponse
		{
			get
			{
				if (this.Results.Contains("msdyn_experimentVersionResponse"))
				{
					return ((string)(this.Results["msdyn_experimentVersionResponse"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
