#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_UpdateRITenantInfo")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_UpdateRITenantInfoRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string HubName
		{
			get
			{
				if (this.Parameters.Contains("HubName"))
				{
					return ((string)(this.Parameters["HubName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["HubName"] = value;
			}
		}
		
		public string PrimaryKey
		{
			get
			{
				if (this.Parameters.Contains("PrimaryKey"))
				{
					return ((string)(this.Parameters["PrimaryKey"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PrimaryKey"] = value;
			}
		}
		
		public msdyn_UpdateRITenantInfoRequest()
		{
			this.RequestName = "msdyn_UpdateRITenantInfo";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_UpdateRITenantInfo")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_UpdateRITenantInfoResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_UpdateRITenantInfoResponse()
		{
		}
	}
}
#pragma warning restore CS1591
