#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_RetrieveKpiItemRecord")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_RetrieveKpiItemRecordRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference CrmRecord
		{
			get
			{
				if (this.Parameters.Contains("CrmRecord"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["CrmRecord"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["CrmRecord"] = value;
			}
		}
		
		public msdyn_RetrieveKpiItemRecordRequest()
		{
			this.RequestName = "msdyn_RetrieveKpiItemRecord";
			this.CrmRecord = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_RetrieveKpiItemRecord")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_RetrieveKpiItemRecordResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_RetrieveKpiItemRecordResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity KpiItemRecord
		{
			get
			{
				if (this.Results.Contains("KpiItemRecord"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["KpiItemRecord"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
		}
		
		public string LastModifiedOn
		{
			get
			{
				if (this.Results.Contains("LastModifiedOn"))
				{
					return ((string)(this.Results["LastModifiedOn"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
