#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ActivateRoutingRule")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ActivateRoutingRuleRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_routingRuleId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_routingRuleId"))
				{
					return ((string)(this.Parameters["msdyn_routingRuleId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_routingRuleId"] = value;
			}
		}
		
		public string msdyn_ownerId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_ownerId"))
				{
					return ((string)(this.Parameters["msdyn_ownerId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_ownerId"] = value;
			}
		}
		
		public msdyn_ActivateRoutingRuleRequest()
		{
			this.RequestName = "msdyn_ActivateRoutingRule";
			this.msdyn_routingRuleId = default(string);
			this.msdyn_ownerId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ActivateRoutingRule")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ActivateRoutingRuleResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ActivateRoutingRuleResponse()
		{
		}
	}
}
#pragma warning restore CS1591
