#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_OCResetLastMessageInfo")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_OCResetLastMessageInfoRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string LiveWorkItemId
		{
			get
			{
				if (this.Parameters.Contains("LiveWorkItemId"))
				{
					return ((string)(this.Parameters["LiveWorkItemId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["LiveWorkItemId"] = value;
			}
		}
		
		public msdyn_OCResetLastMessageInfoRequest()
		{
			this.RequestName = "msdyn_OCResetLastMessageInfo";
			this.LiveWorkItemId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_OCResetLastMessageInfo")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_OCResetLastMessageInfoResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_OCResetLastMessageInfoResponse()
		{
		}
		
		public string ResponseData
		{
			get
			{
				if (this.Results.Contains("ResponseData"))
				{
					return ((string)(this.Results["ResponseData"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
