#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetKeywords")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetKeywordsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_activityId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_activityId"))
				{
					return ((string)(this.Parameters["msdyn_activityId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_activityId"] = value;
			}
		}
		
		public string msdyn_entityName
		{
			get
			{
				if (this.Parameters.Contains("msdyn_entityName"))
				{
					return ((string)(this.Parameters["msdyn_entityName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_entityName"] = value;
			}
		}
		
		public string msdyn_entityType
		{
			get
			{
				if (this.Parameters.Contains("msdyn_entityType"))
				{
					return ((string)(this.Parameters["msdyn_entityType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_entityType"] = value;
			}
		}
		
		public string msdyn_queryLocale
		{
			get
			{
				if (this.Parameters.Contains("msdyn_queryLocale"))
				{
					return ((string)(this.Parameters["msdyn_queryLocale"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_queryLocale"] = value;
			}
		}
		
		public string msdyn_userquery
		{
			get
			{
				if (this.Parameters.Contains("msdyn_userquery"))
				{
					return ((string)(this.Parameters["msdyn_userquery"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_userquery"] = value;
			}
		}
		
		public msdyn_GetKeywordsRequest()
		{
			this.RequestName = "msdyn_GetKeywords";
			this.msdyn_userquery = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetKeywords")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetKeywordsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetKeywordsResponse()
		{
		}
		
		public string msdyn_response
		{
			get
			{
				if (this.Results.Contains("msdyn_response"))
				{
					return ((string)(this.Results["msdyn_response"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
