#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_InsertTrainingRecords")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_InsertTrainingRecordsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public int AttributesCount
		{
			get
			{
				if (this.Parameters.Contains("AttributesCount"))
				{
					return ((int)(this.Parameters["AttributesCount"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["AttributesCount"] = value;
			}
		}
		
		public string Input
		{
			get
			{
				if (this.Parameters.Contains("Input"))
				{
					return ((string)(this.Parameters["Input"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Input"] = value;
			}
		}
		
		public string Config
		{
			get
			{
				if (this.Parameters.Contains("Config"))
				{
					return ((string)(this.Parameters["Config"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Config"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public msdyn_InsertTrainingRecordsRequest()
		{
			this.RequestName = "msdyn_InsertTrainingRecords";
			this.AttributesCount = default(int);
			this.Input = default(string);
			this.Config = default(string);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_InsertTrainingRecords")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_InsertTrainingRecordsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_InsertTrainingRecordsResponse()
		{
		}
		
		public int recordsInserted
		{
			get
			{
				if (this.Results.Contains("recordsInserted"))
				{
					return ((int)(this.Results["recordsInserted"]));
				}
				else
				{
					return default(int);
				}
			}
		}
		
		public int recordsSkipped
		{
			get
			{
				if (this.Results.Contains("recordsSkipped"))
				{
					return ((int)(this.Results["recordsSkipped"]));
				}
				else
				{
					return default(int);
				}
			}
		}
	}
}
#pragma warning restore CS1591
