#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ExecuteRecurringSalesOperation")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ExecuteRecurringSalesOperationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string InputData
		{
			get
			{
				if (this.Parameters.Contains("InputData"))
				{
					return ((string)(this.Parameters["InputData"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["InputData"] = value;
			}
		}
		
		public bool IsRSAV2Entity
		{
			get
			{
				if (this.Parameters.Contains("IsRSAV2Entity"))
				{
					return ((bool)(this.Parameters["IsRSAV2Entity"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["IsRSAV2Entity"] = value;
			}
		}
		
		public string CustomActionName
		{
			get
			{
				if (this.Parameters.Contains("CustomActionName"))
				{
					return ((string)(this.Parameters["CustomActionName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CustomActionName"] = value;
			}
		}
		
		public string TriggerName
		{
			get
			{
				if (this.Parameters.Contains("TriggerName"))
				{
					return ((string)(this.Parameters["TriggerName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["TriggerName"] = value;
			}
		}
		
		public msdyn_ExecuteRecurringSalesOperationRequest()
		{
			this.RequestName = "msdyn_ExecuteRecurringSalesOperation";
			this.CustomActionName = default(string);
			this.TriggerName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ExecuteRecurringSalesOperation")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ExecuteRecurringSalesOperationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ExecuteRecurringSalesOperationResponse()
		{
		}
	}
}
#pragma warning restore CS1591
