#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetSankeyViewKPIs")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetSankeyViewKPIsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string ActionIds
		{
			get
			{
				if (this.Parameters.Contains("ActionIds"))
				{
					return ((string)(this.Parameters["ActionIds"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ActionIds"] = value;
			}
		}
		
		public string SequenceId
		{
			get
			{
				if (this.Parameters.Contains("SequenceId"))
				{
					return ((string)(this.Parameters["SequenceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SequenceId"] = value;
			}
		}
		
		public string RegardingEntityName
		{
			get
			{
				if (this.Parameters.Contains("RegardingEntityName"))
				{
					return ((string)(this.Parameters["RegardingEntityName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RegardingEntityName"] = value;
			}
		}
		
		public msdyn_GetSankeyViewKPIsRequest()
		{
			this.RequestName = "msdyn_GetSankeyViewKPIs";
			this.ActionIds = default(string);
			this.SequenceId = default(string);
			this.RegardingEntityName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetSankeyViewKPIs")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetSankeyViewKPIsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetSankeyViewKPIsResponse()
		{
		}
		
		public string SankeyViewKPIs
		{
			get
			{
				if (this.Results.Contains("SankeyViewKPIs"))
				{
					return ((string)(this.Results["SankeyViewKPIs"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
