#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SuggestPrimaryForMergeAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SuggestPrimaryForMergeActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityCollection RecordList
		{
			get
			{
				if (this.Parameters.Contains("RecordList"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["RecordList"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["RecordList"] = value;
			}
		}
		
		public msdyn_SuggestPrimaryForMergeActionRequest()
		{
			this.RequestName = "msdyn_SuggestPrimaryForMergeAction";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SuggestPrimaryForMergeAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SuggestPrimaryForMergeActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_SuggestPrimaryForMergeActionResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference PrimarySuggestion
		{
			get
			{
				if (this.Results.Contains("PrimarySuggestion"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["PrimarySuggestion"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
		}
	}
}
#pragma warning restore CS1591
