#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetAuditState")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetAuditStateRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public msdyn_GetAuditStateRequest()
		{
			this.RequestName = "msdyn_GetAuditState";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetAuditState")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetAuditStateResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetAuditStateResponse()
		{
		}
		
		public string msdyn_output
		{
			get
			{
				if (this.Results.Contains("msdyn_output"))
				{
					return ((string)(this.Results["msdyn_output"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
