#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CreateDraftResponseForAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_CreateDraftResponseForActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_input
		{
			get
			{
				if (this.Parameters.Contains("msdyn_input"))
				{
					return ((string)(this.Parameters["msdyn_input"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_input"] = value;
			}
		}
		
		public msdyn_CreateDraftResponseForActionRequest()
		{
			this.RequestName = "msdyn_CreateDraftResponseForAction";
			this.msdyn_input = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_CreateDraftResponseForAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_CreateDraftResponseForActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_CreateDraftResponseForActionResponse()
		{
		}
		
		public int msdyn_actionType
		{
			get
			{
				if (this.Results.Contains("msdyn_actionType"))
				{
					return ((int)(this.Results["msdyn_actionType"]));
				}
				else
				{
					return default(int);
				}
			}
		}
		
		public string[] msdyn_cc
		{
			get
			{
				if (this.Results.Contains("msdyn_cc"))
				{
					return ((string[])(this.Results["msdyn_cc"]));
				}
				else
				{
					return default(string[]);
				}
			}
		}
		
		public string msdyn_description
		{
			get
			{
				if (this.Results.Contains("msdyn_description"))
				{
					return ((string)(this.Results["msdyn_description"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdyn_internetMessageId
		{
			get
			{
				if (this.Results.Contains("msdyn_internetMessageId"))
				{
					return ((string)(this.Results["msdyn_internetMessageId"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdyn_messageId
		{
			get
			{
				if (this.Results.Contains("msdyn_messageId"))
				{
					return ((string)(this.Results["msdyn_messageId"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdyn_scheduledEnd
		{
			get
			{
				if (this.Results.Contains("msdyn_scheduledEnd"))
				{
					return ((string)(this.Results["msdyn_scheduledEnd"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdyn_scheduledStart
		{
			get
			{
				if (this.Results.Contains("msdyn_scheduledStart"))
				{
					return ((string)(this.Results["msdyn_scheduledStart"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdyn_subject
		{
			get
			{
				if (this.Results.Contains("msdyn_subject"))
				{
					return ((string)(this.Results["msdyn_subject"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string[] msdyn_to
		{
			get
			{
				if (this.Results.Contains("msdyn_to"))
				{
					return ((string[])(this.Results["msdyn_to"]));
				}
				else
				{
					return default(string[]);
				}
			}
		}
	}
}
#pragma warning restore CS1591
