#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_InitEntityRouting")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_InitEntityRoutingRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string AppInsightsAdditionalInformation
		{
			get
			{
				if (this.Parameters.Contains("AppInsightsAdditionalInformation"))
				{
					return ((string)(this.Parameters["AppInsightsAdditionalInformation"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["AppInsightsAdditionalInformation"] = value;
			}
		}
		
		public string EntityRecordId
		{
			get
			{
				if (this.Parameters.Contains("EntityRecordId"))
				{
					return ((string)(this.Parameters["EntityRecordId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityRecordId"] = value;
			}
		}
		
		public string IntentFamilyId
		{
			get
			{
				if (this.Parameters.Contains("IntentFamilyId"))
				{
					return ((string)(this.Parameters["IntentFamilyId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IntentFamilyId"] = value;
			}
		}
		
		public string IntentId
		{
			get
			{
				if (this.Parameters.Contains("IntentId"))
				{
					return ((string)(this.Parameters["IntentId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IntentId"] = value;
			}
		}
		
		public string AppInsightsEnvInformation
		{
			get
			{
				if (this.Parameters.Contains("AppInsightsEnvInformation"))
				{
					return ((string)(this.Parameters["AppInsightsEnvInformation"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["AppInsightsEnvInformation"] = value;
			}
		}
		
		public string IntentString
		{
			get
			{
				if (this.Parameters.Contains("IntentString"))
				{
					return ((string)(this.Parameters["IntentString"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IntentString"] = value;
			}
		}
		
		public string LiveWorkStreamId
		{
			get
			{
				if (this.Parameters.Contains("LiveWorkStreamId"))
				{
					return ((string)(this.Parameters["LiveWorkStreamId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["LiveWorkStreamId"] = value;
			}
		}
		
		public string EntityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("EntityLogicalName"))
				{
					return ((string)(this.Parameters["EntityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityLogicalName"] = value;
			}
		}
		
		public string IntentGroupId
		{
			get
			{
				if (this.Parameters.Contains("IntentGroupId"))
				{
					return ((string)(this.Parameters["IntentGroupId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IntentGroupId"] = value;
			}
		}
		
		public msdyn_InitEntityRoutingRequest()
		{
			this.RequestName = "msdyn_InitEntityRouting";
			this.EntityRecordId = default(string);
			this.LiveWorkStreamId = default(string);
			this.EntityLogicalName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_InitEntityRouting")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_InitEntityRoutingResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_InitEntityRoutingResponse()
		{
		}
	}
}
#pragma warning restore CS1591
