#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetAutoCaptureUri")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetAutoCaptureUriRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string uriType
		{
			get
			{
				if (this.Parameters.Contains("uriType"))
				{
					return ((string)(this.Parameters["uriType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["uriType"] = value;
			}
		}
		
		public msdyn_GetAutoCaptureUriRequest()
		{
			this.RequestName = "msdyn_GetAutoCaptureUri";
			this.uriType = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetAutoCaptureUri")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetAutoCaptureUriResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetAutoCaptureUriResponse()
		{
		}
		
		public string uri
		{
			get
			{
				if (this.Results.Contains("uri"))
				{
					return ((string)(this.Results["uri"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
