#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_MigrateSequence")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_MigrateSequenceRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string MigrationId
		{
			get
			{
				if (this.Parameters.Contains("MigrationId"))
				{
					return ((string)(this.Parameters["MigrationId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["MigrationId"] = value;
			}
		}
		
		public msdyn_MigrateSequenceRequest()
		{
			this.RequestName = "msdyn_MigrateSequence";
			this.MigrationId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_MigrateSequence")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_MigrateSequenceResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_MigrateSequenceResponse()
		{
		}
	}
}
#pragma warning restore CS1591
