#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_AddTeamsAppToLinkedChat")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_AddTeamsAppToLinkedChatRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public System.Guid msdyn_TeamsChatAssociationId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_TeamsChatAssociationId"))
				{
					return ((System.Guid)(this.Parameters["msdyn_TeamsChatAssociationId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["msdyn_TeamsChatAssociationId"] = value;
			}
		}
		
		public msdyn_AddTeamsAppToLinkedChatRequest()
		{
			this.RequestName = "msdyn_AddTeamsAppToLinkedChat";
			this.msdyn_TeamsChatAssociationId = default(System.Guid);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_AddTeamsAppToLinkedChat")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_AddTeamsAppToLinkedChatResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_AddTeamsAppToLinkedChatResponse()
		{
		}
	}
}
#pragma warning restore CS1591
