#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_RetrieveCadenceSuggestions")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_RetrieveCadenceSuggestionsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference EntityReference
		{
			get
			{
				if (this.Parameters.Contains("EntityReference"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["EntityReference"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["EntityReference"] = value;
			}
		}
		
		public int ActivityType
		{
			get
			{
				if (this.Parameters.Contains("ActivityType"))
				{
					return ((int)(this.Parameters["ActivityType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["ActivityType"] = value;
			}
		}
		
		public string LinkedActivityId
		{
			get
			{
				if (this.Parameters.Contains("LinkedActivityId"))
				{
					return ((string)(this.Parameters["LinkedActivityId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["LinkedActivityId"] = value;
			}
		}
		
		public int StepType
		{
			get
			{
				if (this.Parameters.Contains("StepType"))
				{
					return ((int)(this.Parameters["StepType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["StepType"] = value;
			}
		}
		
		public msdyn_RetrieveCadenceSuggestionsRequest()
		{
			this.RequestName = "msdyn_RetrieveCadenceSuggestions";
			this.EntityReference = default(Microsoft.Xrm.Sdk.EntityReference);
			this.ActivityType = default(int);
			this.StepType = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_RetrieveCadenceSuggestions")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_RetrieveCadenceSuggestionsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_RetrieveCadenceSuggestionsResponse()
		{
		}
		
		public string Suggestions
		{
			get
			{
				if (this.Results.Contains("Suggestions"))
				{
					return ((string)(this.Results["Suggestions"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
