#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CreateApmEventHandler")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_CreateApmEventHandlerRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string AppModuleId
		{
			get
			{
				if (this.Parameters.Contains("AppModuleId"))
				{
					return ((string)(this.Parameters["AppModuleId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["AppModuleId"] = value;
			}
		}
		
		public msdyn_CreateApmEventHandlerRequest()
		{
			this.RequestName = "msdyn_CreateApmEventHandler";
			this.AppModuleId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_CreateApmEventHandler")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_CreateApmEventHandlerResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_CreateApmEventHandlerResponse()
		{
		}
		
		public string UpdateAppModuleResponse
		{
			get
			{
				if (this.Results.Contains("UpdateAppModuleResponse"))
				{
					return ((string)(this.Results["UpdateAppModuleResponse"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
