#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_IsMSTeamsUserSyncFeatureEnabled")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_IsMSTeamsUserSyncFeatureEnabledRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public msdyn_IsMSTeamsUserSyncFeatureEnabledRequest()
		{
			this.RequestName = "msdyn_IsMSTeamsUserSyncFeatureEnabled";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_IsMSTeamsUserSyncFeatureEnabled")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_IsMSTeamsUserSyncFeatureEnabledResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_IsMSTeamsUserSyncFeatureEnabledResponse()
		{
		}
		
		public string DisabledReason
		{
			get
			{
				if (this.Results.Contains("DisabledReason"))
				{
					return ((string)(this.Results["DisabledReason"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public bool IsEnabled
		{
			get
			{
				if (this.Results.Contains("IsEnabled"))
				{
					return ((bool)(this.Results["IsEnabled"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
}
#pragma warning restore CS1591
