#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SetAutoBlockedFlag")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SetAutoBlockedFlagRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.Entity FlaggedSpamEntity
		{
			get
			{
				if (this.Parameters.Contains("FlaggedSpamEntity"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["FlaggedSpamEntity"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Parameters["FlaggedSpamEntity"] = value;
			}
		}
		
		public msdyn_SetAutoBlockedFlagRequest()
		{
			this.RequestName = "msdyn_SetAutoBlockedFlag";
			this.FlaggedSpamEntity = default(Microsoft.Xrm.Sdk.Entity);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SetAutoBlockedFlag")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SetAutoBlockedFlagResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_SetAutoBlockedFlagResponse()
		{
		}
	}
}
#pragma warning restore CS1591
