#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_DismissSuggestedContact")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_DismissSuggestedContactRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string SuggestedContactId
		{
			get
			{
				if (this.Parameters.Contains("SuggestedContactId"))
				{
					return ((string)(this.Parameters["SuggestedContactId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SuggestedContactId"] = value;
			}
		}
		
		public bool DismissContact
		{
			get
			{
				if (this.Parameters.Contains("DismissContact"))
				{
					return ((bool)(this.Parameters["DismissContact"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["DismissContact"] = value;
			}
		}
		
		public msdyn_DismissSuggestedContactRequest()
		{
			this.RequestName = "msdyn_DismissSuggestedContact";
			this.SuggestedContactId = default(string);
			this.DismissContact = default(bool);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_DismissSuggestedContact")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_DismissSuggestedContactResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_DismissSuggestedContactResponse()
		{
		}
	}
}
#pragma warning restore CS1591
