#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_AnalyticsSaveDataInConfigStore")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_AnalyticsSaveDataInConfigStoreRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string Key
		{
			get
			{
				if (this.Parameters.Contains("Key"))
				{
					return ((string)(this.Parameters["Key"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Key"] = value;
			}
		}
		
		public string Value
		{
			get
			{
				if (this.Parameters.Contains("Value"))
				{
					return ((string)(this.Parameters["Value"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Value"] = value;
			}
		}
		
		public string ConfigName
		{
			get
			{
				if (this.Parameters.Contains("ConfigName"))
				{
					return ((string)(this.Parameters["ConfigName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ConfigName"] = value;
			}
		}
		
		public msdyn_AnalyticsSaveDataInConfigStoreRequest()
		{
			this.RequestName = "msdyn_AnalyticsSaveDataInConfigStore";
			this.Key = default(string);
			this.Value = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_AnalyticsSaveDataInConfigStore")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_AnalyticsSaveDataInConfigStoreResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_AnalyticsSaveDataInConfigStoreResponse()
		{
		}
	}
}
#pragma warning restore CS1591
