#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SendRecordEventUpdate")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SendRecordEventUpdateRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_EventType
		{
			get
			{
				if (this.Parameters.Contains("msdyn_EventType"))
				{
					return ((string)(this.Parameters["msdyn_EventType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_EventType"] = value;
			}
		}
		
		public string[] msdyn_AttributeDisplayValues
		{
			get
			{
				if (this.Parameters.Contains("msdyn_AttributeDisplayValues"))
				{
					return ((string[])(this.Parameters["msdyn_AttributeDisplayValues"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["msdyn_AttributeDisplayValues"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference msdyn_RegardingActivity
		{
			get
			{
				if (this.Parameters.Contains("msdyn_RegardingActivity"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["msdyn_RegardingActivity"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["msdyn_RegardingActivity"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference msdyn_RegardingRecord
		{
			get
			{
				if (this.Parameters.Contains("msdyn_RegardingRecord"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["msdyn_RegardingRecord"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["msdyn_RegardingRecord"] = value;
			}
		}
		
		public string[] msdyn_AttributeNames
		{
			get
			{
				if (this.Parameters.Contains("msdyn_AttributeNames"))
				{
					return ((string[])(this.Parameters["msdyn_AttributeNames"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["msdyn_AttributeNames"] = value;
			}
		}
		
		public msdyn_SendRecordEventUpdateRequest()
		{
			this.RequestName = "msdyn_SendRecordEventUpdate";
			this.msdyn_EventType = default(string);
			this.msdyn_RegardingRecord = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SendRecordEventUpdate")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SendRecordEventUpdateResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_SendRecordEventUpdateResponse()
		{
		}
	}
}
#pragma warning restore CS1591
