#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdynmkt/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdynmkt_PredefinedPlaceholderAddCount")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_PredefinedPlaceholderAddCountRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string PredefinedPlaceholderAddCountRequest
		{
			get
			{
				if (this.Parameters.Contains("PredefinedPlaceholderAddCountRequest"))
				{
					return ((string)(this.Parameters["PredefinedPlaceholderAddCountRequest"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PredefinedPlaceholderAddCountRequest"] = value;
			}
		}
		
		public msdynmkt_PredefinedPlaceholderAddCountRequest()
		{
			this.RequestName = "msdynmkt_PredefinedPlaceholderAddCount";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdynmkt/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdynmkt_PredefinedPlaceholderAddCount")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_PredefinedPlaceholderAddCountResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdynmkt_PredefinedPlaceholderAddCountResponse()
		{
		}
	}
}
#pragma warning restore CS1591
