#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_upsertSalesRoutingDiagnostic")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_upsertSalesRoutingDiagnosticRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string Payload
		{
			get
			{
				if (this.Parameters.Contains("Payload"))
				{
					return ((string)(this.Parameters["Payload"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Payload"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.OptionSetValue EventType
		{
			get
			{
				if (this.Parameters.Contains("EventType"))
				{
					return ((Microsoft.Xrm.Sdk.OptionSetValue)(this.Parameters["EventType"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.OptionSetValue);
				}
			}
			set
			{
				this.Parameters["EventType"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference TargetObject
		{
			get
			{
				if (this.Parameters.Contains("TargetObject"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["TargetObject"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["TargetObject"] = value;
			}
		}
		
		public msdyn_upsertSalesRoutingDiagnosticRequest()
		{
			this.RequestName = "msdyn_upsertSalesRoutingDiagnostic";
			this.Payload = default(string);
			this.EventType = default(Microsoft.Xrm.Sdk.OptionSetValue);
			this.TargetObject = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_upsertSalesRoutingDiagnostic")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_upsertSalesRoutingDiagnosticResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_upsertSalesRoutingDiagnosticResponse()
		{
		}
	}
}
#pragma warning restore CS1591
