#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CSAdminCenterAppSolutionHealthRulesRegistration")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_CSAdminCenterAppSolutionHealthRulesRegistrationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string SolutionNames
		{
			get
			{
				if (this.Parameters.Contains("SolutionNames"))
				{
					return ((string)(this.Parameters["SolutionNames"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SolutionNames"] = value;
			}
		}
		
		public msdyn_CSAdminCenterAppSolutionHealthRulesRegistrationRequest()
		{
			this.RequestName = "msdyn_CSAdminCenterAppSolutionHealthRulesRegistration";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_CSAdminCenterAppSolutionHealthRulesRegistration")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_CSAdminCenterAppSolutionHealthRulesRegistrationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_CSAdminCenterAppSolutionHealthRulesRegistrationResponse()
		{
		}
		
		public string Message
		{
			get
			{
				if (this.Results.Contains("Message"))
				{
					return ((string)(this.Results["Message"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public int ReturnStatus
		{
			get
			{
				if (this.Results.Contains("ReturnStatus"))
				{
					return ((int)(this.Results["ReturnStatus"]));
				}
				else
				{
					return default(int);
				}
			}
		}
		
		public string RuleId
		{
			get
			{
				if (this.Results.Contains("RuleId"))
				{
					return ((string)(this.Results["RuleId"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
