#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_InitiateCCaaSAPIsAsync")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_InitiateCCaaSAPIsAsyncRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string Payload
		{
			get
			{
				if (this.Parameters.Contains("Payload"))
				{
					return ((string)(this.Parameters["Payload"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Payload"] = value;
			}
		}
		
		public System.Guid LiveWorkItemId
		{
			get
			{
				if (this.Parameters.Contains("LiveWorkItemId"))
				{
					return ((System.Guid)(this.Parameters["LiveWorkItemId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["LiveWorkItemId"] = value;
			}
		}
		
		public string CCaaSAPI
		{
			get
			{
				if (this.Parameters.Contains("CCaaSAPI"))
				{
					return ((string)(this.Parameters["CCaaSAPI"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CCaaSAPI"] = value;
			}
		}
		
		public System.Guid InitiatingUser
		{
			get
			{
				if (this.Parameters.Contains("InitiatingUser"))
				{
					return ((System.Guid)(this.Parameters["InitiatingUser"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["InitiatingUser"] = value;
			}
		}
		
		public msdyn_InitiateCCaaSAPIsAsyncRequest()
		{
			this.RequestName = "msdyn_InitiateCCaaSAPIsAsync";
			this.Payload = default(string);
			this.LiveWorkItemId = default(System.Guid);
			this.CCaaSAPI = default(string);
			this.InitiatingUser = default(System.Guid);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_InitiateCCaaSAPIsAsync")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_InitiateCCaaSAPIsAsyncResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_InitiateCCaaSAPIsAsyncResponse()
		{
		}
		
		public string msdyn_InitiateCCaaSAPIsAsyncResponse
		{
			get
			{
				if (this.Results.Contains("msdyn_InitiateCCaaSAPIsAsyncResponse"))
				{
					return ((string)(this.Results["msdyn_InitiateCCaaSAPIsAsyncResponse"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
