#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_McMcbyValues")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_McMcbyValuesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference CrmRecord
		{
			get
			{
				if (this.Parameters.Contains("CrmRecord"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["CrmRecord"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["CrmRecord"] = value;
			}
		}
		
		public string KPIType
		{
			get
			{
				if (this.Parameters.Contains("KPIType"))
				{
					return ((string)(this.Parameters["KPIType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["KPIType"] = value;
			}
		}
		
		public msdyn_McMcbyValuesRequest()
		{
			this.RequestName = "msdyn_McMcbyValues";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_McMcbyValues")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_McMcbyValuesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_McMcbyValuesResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection KPIValues
		{
			get
			{
				if (this.Results.Contains("KPIValues"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["KPIValues"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
		}
		
		public string LastModifiedOn
		{
			get
			{
				if (this.Results.Contains("LastModifiedOn"))
				{
					return ((string)(this.Results["LastModifiedOn"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
