#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_AddSuggestedCards")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_AddSuggestedCardsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string scope
		{
			get
			{
				if (this.Parameters.Contains("scope"))
				{
					return ((string)(this.Parameters["scope"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["scope"] = value;
			}
		}
		
		public string BusinessProcessFlowId
		{
			get
			{
				if (this.Parameters.Contains("BusinessProcessFlowId"))
				{
					return ((string)(this.Parameters["BusinessProcessFlowId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BusinessProcessFlowId"] = value;
			}
		}
		
		public string BusinessProcessFlowInstanceId
		{
			get
			{
				if (this.Parameters.Contains("BusinessProcessFlowInstanceId"))
				{
					return ((string)(this.Parameters["BusinessProcessFlowInstanceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BusinessProcessFlowInstanceId"] = value;
			}
		}
		
		public string ActionStepId
		{
			get
			{
				if (this.Parameters.Contains("ActionStepId"))
				{
					return ((string)(this.Parameters["ActionStepId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ActionStepId"] = value;
			}
		}
		
		public msdyn_AddSuggestedCardsRequest()
		{
			this.RequestName = "msdyn_AddSuggestedCards";
			this.scope = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_AddSuggestedCards")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_AddSuggestedCardsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_AddSuggestedCardsResponse()
		{
		}
	}
}
#pragma warning restore CS1591
