#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_FetchAllPredictionModels")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_FetchAllPredictionModelsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string PredictionType
		{
			get
			{
				if (this.Parameters.Contains("PredictionType"))
				{
					return ((string)(this.Parameters["PredictionType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PredictionType"] = value;
			}
		}
		
		public msdyn_FetchAllPredictionModelsRequest()
		{
			this.RequestName = "msdyn_FetchAllPredictionModels";
			this.PredictionType = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_FetchAllPredictionModels")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_FetchAllPredictionModelsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_FetchAllPredictionModelsResponse()
		{
		}
		
		public string Response
		{
			get
			{
				if (this.Results.Contains("Response"))
				{
					return ((string)(this.Results["Response"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
