#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetOrCreateLinkedActivity")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetOrCreateLinkedActivityRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string SequenceStepId
		{
			get
			{
				if (this.Parameters.Contains("SequenceStepId"))
				{
					return ((string)(this.Parameters["SequenceStepId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SequenceStepId"] = value;
			}
		}
		
		public bool CreateLinkedActivity
		{
			get
			{
				if (this.Parameters.Contains("CreateLinkedActivity"))
				{
					return ((bool)(this.Parameters["CreateLinkedActivity"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["CreateLinkedActivity"] = value;
			}
		}
		
		public msdyn_GetOrCreateLinkedActivityRequest()
		{
			this.RequestName = "msdyn_GetOrCreateLinkedActivity";
			this.SequenceStepId = default(string);
			this.CreateLinkedActivity = default(bool);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetOrCreateLinkedActivity")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetOrCreateLinkedActivityResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetOrCreateLinkedActivityResponse()
		{
		}
		
		public bool IsLinkedActivityCreated
		{
			get
			{
				if (this.Results.Contains("IsLinkedActivityCreated"))
				{
					return ((bool)(this.Results["IsLinkedActivityCreated"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
		
		public string LinkedActivityId
		{
			get
			{
				if (this.Results.Contains("LinkedActivityId"))
				{
					return ((string)(this.Results["LinkedActivityId"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
