#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdynmkt_GetDataverseTableMetadataItems")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_GetDataverseTableMetadataItemsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string[] msdynmkt_GetDataverseTableMetadataItems_request_SourceLogicalNames
		{
			get
			{
				if (this.Parameters.Contains("msdynmkt_GetDataverseTableMetadataItems_request_SourceLogicalNames"))
				{
					return ((string[])(this.Parameters["msdynmkt_GetDataverseTableMetadataItems_request_SourceLogicalNames"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["msdynmkt_GetDataverseTableMetadataItems_request_SourceLogicalNames"] = value;
			}
		}
		
		public bool msdynmkt_GetDataverseTableMetadataItems_request_UseLazyLoading
		{
			get
			{
				if (this.Parameters.Contains("msdynmkt_GetDataverseTableMetadataItems_request_UseLazyLoading"))
				{
					return ((bool)(this.Parameters["msdynmkt_GetDataverseTableMetadataItems_request_UseLazyLoading"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["msdynmkt_GetDataverseTableMetadataItems_request_UseLazyLoading"] = value;
			}
		}
		
		public int msdynmkt_GetDataverseTableMetadataItems_request_LanguageCode
		{
			get
			{
				if (this.Parameters.Contains("msdynmkt_GetDataverseTableMetadataItems_request_LanguageCode"))
				{
					return ((int)(this.Parameters["msdynmkt_GetDataverseTableMetadataItems_request_LanguageCode"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["msdynmkt_GetDataverseTableMetadataItems_request_LanguageCode"] = value;
			}
		}
		
		public msdynmkt_GetDataverseTableMetadataItemsRequest()
		{
			this.RequestName = "msdynmkt_GetDataverseTableMetadataItems";
			this.msdynmkt_GetDataverseTableMetadataItems_request_SourceLogicalNames = default(string[]);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdynmkt_GetDataverseTableMetadataItems")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_GetDataverseTableMetadataItemsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdynmkt_GetDataverseTableMetadataItemsResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection msdynmkt_GetDataverseTableMetadataItems_response_items
		{
			get
			{
				if (this.Results.Contains("msdynmkt_GetDataverseTableMetadataItems_response_items"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["msdynmkt_GetDataverseTableMetadataItems_response_items"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
		}
	}
}
#pragma warning restore CS1591
