#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ActionCardActionLogger")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ActionCardActionLoggerRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public int cardType
		{
			get
			{
				if (this.Parameters.Contains("cardType"))
				{
					return ((int)(this.Parameters["cardType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["cardType"] = value;
			}
		}
		
		public string userId
		{
			get
			{
				if (this.Parameters.Contains("userId"))
				{
					return ((string)(this.Parameters["userId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["userId"] = value;
			}
		}
		
		public string cardTypeId
		{
			get
			{
				if (this.Parameters.Contains("cardTypeId"))
				{
					return ((string)(this.Parameters["cardTypeId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["cardTypeId"] = value;
			}
		}
		
		public string actionType
		{
			get
			{
				if (this.Parameters.Contains("actionType"))
				{
					return ((string)(this.Parameters["actionType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["actionType"] = value;
			}
		}
		
		public int totalActions
		{
			get
			{
				if (this.Parameters.Contains("totalActions"))
				{
					return ((int)(this.Parameters["totalActions"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["totalActions"] = value;
			}
		}
		
		public string actionCardId
		{
			get
			{
				if (this.Parameters.Contains("actionCardId"))
				{
					return ((string)(this.Parameters["actionCardId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["actionCardId"] = value;
			}
		}
		
		public string regardingObjectId
		{
			get
			{
				if (this.Parameters.Contains("regardingObjectId"))
				{
					return ((string)(this.Parameters["regardingObjectId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["regardingObjectId"] = value;
			}
		}
		
		public string regardingObjectLogicalName
		{
			get
			{
				if (this.Parameters.Contains("regardingObjectLogicalName"))
				{
					return ((string)(this.Parameters["regardingObjectLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["regardingObjectLogicalName"] = value;
			}
		}
		
		public int regardingObjectTypeCode
		{
			get
			{
				if (this.Parameters.Contains("regardingObjectTypeCode"))
				{
					return ((int)(this.Parameters["regardingObjectTypeCode"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["regardingObjectTypeCode"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public msdyn_ActionCardActionLoggerRequest()
		{
			this.RequestName = "msdyn_ActionCardActionLogger";
			this.userId = default(string);
			this.cardTypeId = default(string);
			this.actionType = default(string);
			this.totalActions = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ActionCardActionLogger")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ActionCardActionLoggerResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ActionCardActionLoggerResponse()
		{
		}
	}
}
#pragma warning restore CS1591
