#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetSalesAcceleratedSeller")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetSalesAcceleratedSellerRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public bool IsTeamsRequest
		{
			get
			{
				if (this.Parameters.Contains("IsTeamsRequest"))
				{
					return ((bool)(this.Parameters["IsTeamsRequest"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["IsTeamsRequest"] = value;
			}
		}
		
		public bool ExpandDetails
		{
			get
			{
				if (this.Parameters.Contains("ExpandDetails"))
				{
					return ((bool)(this.Parameters["ExpandDetails"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ExpandDetails"] = value;
			}
		}
		
		public msdyn_GetSalesAcceleratedSellerRequest()
		{
			this.RequestName = "msdyn_GetSalesAcceleratedSeller";
			this.IsTeamsRequest = default(bool);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetSalesAcceleratedSeller")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetSalesAcceleratedSellerResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetSalesAcceleratedSellerResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection SellerList
		{
			get
			{
				if (this.Results.Contains("SellerList"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["SellerList"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
		}
	}
}
#pragma warning restore CS1591
