#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ExecuteCopilotServiceJob")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ExecuteCopilotServiceJobRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public int msdyn_AuthFlowType
		{
			get
			{
				if (this.Parameters.Contains("msdyn_AuthFlowType"))
				{
					return ((int)(this.Parameters["msdyn_AuthFlowType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["msdyn_AuthFlowType"] = value;
			}
		}
		
		public int msdyn_JobType
		{
			get
			{
				if (this.Parameters.Contains("msdyn_JobType"))
				{
					return ((int)(this.Parameters["msdyn_JobType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["msdyn_JobType"] = value;
			}
		}
		
		public string msdyn_JobPayload
		{
			get
			{
				if (this.Parameters.Contains("msdyn_JobPayload"))
				{
					return ((string)(this.Parameters["msdyn_JobPayload"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_JobPayload"] = value;
			}
		}
		
		public msdyn_ExecuteCopilotServiceJobRequest()
		{
			this.RequestName = "msdyn_ExecuteCopilotServiceJob";
			this.msdyn_JobType = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ExecuteCopilotServiceJob")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ExecuteCopilotServiceJobResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ExecuteCopilotServiceJobResponse()
		{
		}
	}
}
#pragma warning restore CS1591
