#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CreateCustomActionDefinition")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_CreateCustomActionDefinitionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string customActionParams
		{
			get
			{
				if (this.Parameters.Contains("customActionParams"))
				{
					return ((string)(this.Parameters["customActionParams"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["customActionParams"] = value;
			}
		}
		
		public System.Guid correlationId
		{
			get
			{
				if (this.Parameters.Contains("correlationId"))
				{
					return ((System.Guid)(this.Parameters["correlationId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["correlationId"] = value;
			}
		}
		
		public string entityName
		{
			get
			{
				if (this.Parameters.Contains("entityName"))
				{
					return ((string)(this.Parameters["entityName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entityName"] = value;
			}
		}
		
		public System.Guid workflowId
		{
			get
			{
				if (this.Parameters.Contains("workflowId"))
				{
					return ((System.Guid)(this.Parameters["workflowId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["workflowId"] = value;
			}
		}
		
		public string customAction
		{
			get
			{
				if (this.Parameters.Contains("customAction"))
				{
					return ((string)(this.Parameters["customAction"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["customAction"] = value;
			}
		}
		
		public msdyn_CreateCustomActionDefinitionRequest()
		{
			this.RequestName = "msdyn_CreateCustomActionDefinition";
			this.customActionParams = default(string);
			this.correlationId = default(System.Guid);
			this.entityName = default(string);
			this.workflowId = default(System.Guid);
			this.customAction = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_CreateCustomActionDefinition")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_CreateCustomActionDefinitionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_CreateCustomActionDefinitionResponse()
		{
		}
		
		public string actionDetails
		{
			get
			{
				if (this.Results.Contains("actionDetails"))
				{
					return ((string)(this.Results["actionDetails"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
