#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_LogPlatformSummaryInteraction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_LogPlatformSummaryInteractionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string InteractionType
		{
			get
			{
				if (this.Parameters.Contains("InteractionType"))
				{
					return ((string)(this.Parameters["InteractionType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["InteractionType"] = value;
			}
		}
		
		public string InteractionData
		{
			get
			{
				if (this.Parameters.Contains("InteractionData"))
				{
					return ((string)(this.Parameters["InteractionData"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["InteractionData"] = value;
			}
		}
		
		public string Context
		{
			get
			{
				if (this.Parameters.Contains("Context"))
				{
					return ((string)(this.Parameters["Context"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Context"] = value;
			}
		}
		
		public msdyn_LogPlatformSummaryInteractionRequest()
		{
			this.RequestName = "msdyn_LogPlatformSummaryInteraction";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_LogPlatformSummaryInteraction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_LogPlatformSummaryInteractionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_LogPlatformSummaryInteractionResponse()
		{
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
