#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ConvertSequenceJsonToCJOJson")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ConvertSequenceJsonToCJOJsonRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string SequenceId
		{
			get
			{
				if (this.Parameters.Contains("SequenceId"))
				{
					return ((string)(this.Parameters["SequenceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SequenceId"] = value;
			}
		}
		
		public msdyn_ConvertSequenceJsonToCJOJsonRequest()
		{
			this.RequestName = "msdyn_ConvertSequenceJsonToCJOJson";
			this.SequenceId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ConvertSequenceJsonToCJOJson")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ConvertSequenceJsonToCJOJsonResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ConvertSequenceJsonToCJOJsonResponse()
		{
		}
		
		public bool Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((bool)(this.Results["Result"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
}
#pragma warning restore CS1591
