#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdynmkt/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdynmkt_PersonalizationGetEntityTypes")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_PersonalizationGetEntityTypesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string GetEntityTypesRequest
		{
			get
			{
				if (this.Parameters.Contains("GetEntityTypesRequest"))
				{
					return ((string)(this.Parameters["GetEntityTypesRequest"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["GetEntityTypesRequest"] = value;
			}
		}
		
		public msdynmkt_PersonalizationGetEntityTypesRequest()
		{
			this.RequestName = "msdynmkt_PersonalizationGetEntityTypes";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdynmkt/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdynmkt_PersonalizationGetEntityTypes")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_PersonalizationGetEntityTypesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdynmkt_PersonalizationGetEntityTypesResponse()
		{
		}
		
		public string GetEntityTypesResult
		{
			get
			{
				if (this.Results.Contains("GetEntityTypesResult"))
				{
					return ((string)(this.Results["GetEntityTypesResult"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
