#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CustomApiCustomerServiceCaseSummary")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_CustomApiCustomerServiceCaseSummaryRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_CaseNumber
		{
			get
			{
				if (this.Parameters.Contains("msdyn_CaseNumber"))
				{
					return ((string)(this.Parameters["msdyn_CaseNumber"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_CaseNumber"] = value;
			}
		}
		
		public msdyn_CustomApiCustomerServiceCaseSummaryRequest()
		{
			this.RequestName = "msdyn_CustomApiCustomerServiceCaseSummary";
			this.msdyn_CaseNumber = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_CustomApiCustomerServiceCaseSummary")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_CustomApiCustomerServiceCaseSummaryResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_CustomApiCustomerServiceCaseSummaryResponse()
		{
		}
		
		public string msdyn_CaseSummary
		{
			get
			{
				if (this.Results.Contains("msdyn_CaseSummary"))
				{
					return ((string)(this.Results["msdyn_CaseSummary"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
