#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ResetOmnichannelProvider")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ResetOmnichannelProviderRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string OrgBaseUrl
		{
			get
			{
				if (this.Parameters.Contains("OrgBaseUrl"))
				{
					return ((string)(this.Parameters["OrgBaseUrl"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["OrgBaseUrl"] = value;
			}
		}
		
		public msdyn_ResetOmnichannelProviderRequest()
		{
			this.RequestName = "msdyn_ResetOmnichannelProvider";
			this.OrgBaseUrl = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ResetOmnichannelProvider")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ResetOmnichannelProviderResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ResetOmnichannelProviderResponse()
		{
		}
	}
}
#pragma warning restore CS1591
