#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_fetchemailsentimentsapi")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_fetchemailsentimentsapiRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string entityid
		{
			get
			{
				if (this.Parameters.Contains("entityid"))
				{
					return ((string)(this.Parameters["entityid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entityid"] = value;
			}
		}
		
		public string entitylogicalname
		{
			get
			{
				if (this.Parameters.Contains("entitylogicalname"))
				{
					return ((string)(this.Parameters["entitylogicalname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entitylogicalname"] = value;
			}
		}
		
		public msdyn_fetchemailsentimentsapiRequest()
		{
			this.RequestName = "msdyn_fetchemailsentimentsapi";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_fetchemailsentimentsapi")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_fetchemailsentimentsapiResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_fetchemailsentimentsapiResponse()
		{
		}
		
		public string emailsentimentsapijson
		{
			get
			{
				if (this.Results.Contains("emailsentimentsapijson"))
				{
					return ((string)(this.Results["emailsentimentsapijson"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
