#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_InvokeIntelligenceAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_InvokeIntelligenceActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string RequestPayload
		{
			get
			{
				if (this.Parameters.Contains("RequestPayload"))
				{
					return ((string)(this.Parameters["RequestPayload"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RequestPayload"] = value;
			}
		}
		
		public string Context
		{
			get
			{
				if (this.Parameters.Contains("Context"))
				{
					return ((string)(this.Parameters["Context"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Context"] = value;
			}
		}
		
		public string ScenarioType
		{
			get
			{
				if (this.Parameters.Contains("ScenarioType"))
				{
					return ((string)(this.Parameters["ScenarioType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ScenarioType"] = value;
			}
		}
		
		public msdyn_InvokeIntelligenceActionRequest()
		{
			this.RequestName = "msdyn_InvokeIntelligenceAction";
			this.RequestPayload = default(string);
			this.ScenarioType = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_InvokeIntelligenceAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_InvokeIntelligenceActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_InvokeIntelligenceActionResponse()
		{
		}
		
		public string Metadata
		{
			get
			{
				if (this.Results.Contains("Metadata"))
				{
					return ((string)(this.Results["Metadata"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
