#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_d365autoinstall")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_d365autoinstallRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public bool ShouldNotifyInApp
		{
			get
			{
				if (this.Parameters.Contains("ShouldNotifyInApp"))
				{
					return ((bool)(this.Parameters["ShouldNotifyInApp"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ShouldNotifyInApp"] = value;
			}
		}
		
		public msdyn_d365autoinstallRequest()
		{
			this.RequestName = "msdyn_d365autoinstall";
			this.ShouldNotifyInApp = default(bool);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_d365autoinstall")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_d365autoinstallResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_d365autoinstallResponse()
		{
		}
		
		public bool ShouldNotify
		{
			get
			{
				if (this.Results.Contains("ShouldNotify"))
				{
					return ((bool)(this.Results["ShouldNotify"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
}
#pragma warning restore CS1591
