#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SetFeatureStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SetFeatureStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public int FeatureType
		{
			get
			{
				if (this.Parameters.Contains("FeatureType"))
				{
					return ((int)(this.Parameters["FeatureType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["FeatureType"] = value;
			}
		}
		
		public bool Status
		{
			get
			{
				if (this.Parameters.Contains("Status"))
				{
					return ((bool)(this.Parameters["Status"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["Status"] = value;
			}
		}
		
		public bool IsSolutionUninstall
		{
			get
			{
				if (this.Parameters.Contains("IsSolutionUninstall"))
				{
					return ((bool)(this.Parameters["IsSolutionUninstall"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["IsSolutionUninstall"] = value;
			}
		}
		
		public string ConfigurationData
		{
			get
			{
				if (this.Parameters.Contains("ConfigurationData"))
				{
					return ((string)(this.Parameters["ConfigurationData"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ConfigurationData"] = value;
			}
		}
		
		public msdyn_SetFeatureStatusRequest()
		{
			this.RequestName = "msdyn_SetFeatureStatus";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SetFeatureStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SetFeatureStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_SetFeatureStatusResponse()
		{
		}
	}
}
#pragma warning restore CS1591
