#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SalesOutlookMeetingPreparation")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SalesOutlookMeetingPreparationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_id
		{
			get
			{
				if (this.Parameters.Contains("msdyn_id"))
				{
					return ((string)(this.Parameters["msdyn_id"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_id"] = value;
			}
		}
		
		public string msdyn_type
		{
			get
			{
				if (this.Parameters.Contains("msdyn_type"))
				{
					return ((string)(this.Parameters["msdyn_type"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_type"] = value;
			}
		}
		
		public msdyn_SalesOutlookMeetingPreparationRequest()
		{
			this.RequestName = "msdyn_SalesOutlookMeetingPreparation";
			this.msdyn_id = default(string);
			this.msdyn_type = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SalesOutlookMeetingPreparation")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SalesOutlookMeetingPreparationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_SalesOutlookMeetingPreparationResponse()
		{
		}
		
		public string msdyn_error
		{
			get
			{
				if (this.Results.Contains("msdyn_error"))
				{
					return ((string)(this.Results["msdyn_error"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdyn_result
		{
			get
			{
				if (this.Results.Contains("msdyn_result"))
				{
					return ((string)(this.Results["msdyn_result"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public int msdyn_status
		{
			get
			{
				if (this.Results.Contains("msdyn_status"))
				{
					return ((int)(this.Results["msdyn_status"]));
				}
				else
				{
					return default(int);
				}
			}
		}
	}
}
#pragma warning restore CS1591
