#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetSwarmParticipantDetails")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetSwarmParticipantDetailsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_SwarmParticipantId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_SwarmParticipantId"))
				{
					return ((string)(this.Parameters["msdyn_SwarmParticipantId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_SwarmParticipantId"] = value;
			}
		}
		
		public msdyn_GetSwarmParticipantDetailsRequest()
		{
			this.RequestName = "msdyn_GetSwarmParticipantDetails";
			this.msdyn_SwarmParticipantId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetSwarmParticipantDetails")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetSwarmParticipantDetailsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetSwarmParticipantDetailsResponse()
		{
		}
		
		public string msdyn_PersonaObject
		{
			get
			{
				if (this.Results.Contains("msdyn_PersonaObject"))
				{
					return ((string)(this.Results["msdyn_PersonaObject"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
