#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CreateKBArticle")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_CreateKBArticleRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string CSCopilotRequest2
		{
			get
			{
				if (this.Parameters.Contains("CSCopilotRequest2"))
				{
					return ((string)(this.Parameters["CSCopilotRequest2"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CSCopilotRequest2"] = value;
			}
		}
		
		public msdyn_CreateKBArticleRequest()
		{
			this.RequestName = "msdyn_CreateKBArticle";
			this.CSCopilotRequest2 = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_CreateKBArticle")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_CreateKBArticleResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_CreateKBArticleResponse()
		{
		}
		
		public string Response2
		{
			get
			{
				if (this.Results.Contains("Response2"))
				{
					return ((string)(this.Results["Response2"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
