#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdynmkt/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdynmkt_ValueWidgetDataCustomAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_ValueWidgetDataCustomActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string WidgetRequest
		{
			get
			{
				if (this.Parameters.Contains("WidgetRequest"))
				{
					return ((string)(this.Parameters["WidgetRequest"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["WidgetRequest"] = value;
			}
		}
		
		public msdynmkt_ValueWidgetDataCustomActionRequest()
		{
			this.RequestName = "msdynmkt_ValueWidgetDataCustomAction";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdynmkt/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdynmkt_ValueWidgetDataCustomAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_ValueWidgetDataCustomActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdynmkt_ValueWidgetDataCustomActionResponse()
		{
		}
		
		public string ErrorMessage
		{
			get
			{
				if (this.Results.Contains("ErrorMessage"))
				{
					return ((string)(this.Results["ErrorMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public bool IsSuccess
		{
			get
			{
				if (this.Results.Contains("IsSuccess"))
				{
					return ((bool)(this.Results["IsSuccess"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
		
		public int StatusCode
		{
			get
			{
				if (this.Results.Contains("StatusCode"))
				{
					return ((int)(this.Results["StatusCode"]));
				}
				else
				{
					return default(int);
				}
			}
		}
		
		public string WidgetData
		{
			get
			{
				if (this.Results.Contains("WidgetData"))
				{
					return ((string)(this.Results["WidgetData"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string WidgetDefinition
		{
			get
			{
				if (this.Results.Contains("WidgetDefinition"))
				{
					return ((string)(this.Results["WidgetDefinition"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
