#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdynmkt_RetrieveAnalyitcsAriaCounts")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_RetrieveAnalyitcsAriaCountsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdynmkt_ariacountsrequest
		{
			get
			{
				if (this.Parameters.Contains("msdynmkt_ariacountsrequest"))
				{
					return ((string)(this.Parameters["msdynmkt_ariacountsrequest"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdynmkt_ariacountsrequest"] = value;
			}
		}
		
		public string msdynmkt_appname
		{
			get
			{
				if (this.Parameters.Contains("msdynmkt_appname"))
				{
					return ((string)(this.Parameters["msdynmkt_appname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdynmkt_appname"] = value;
			}
		}
		
		public string msdynmkt_primaryrecordid
		{
			get
			{
				if (this.Parameters.Contains("msdynmkt_primaryrecordid"))
				{
					return ((string)(this.Parameters["msdynmkt_primaryrecordid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdynmkt_primaryrecordid"] = value;
			}
		}
		
		public string msdynmkt_primaryrecordentityname
		{
			get
			{
				if (this.Parameters.Contains("msdynmkt_primaryrecordentityname"))
				{
					return ((string)(this.Parameters["msdynmkt_primaryrecordentityname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdynmkt_primaryrecordentityname"] = value;
			}
		}
		
		public msdynmkt_RetrieveAnalyitcsAriaCountsRequest()
		{
			this.RequestName = "msdynmkt_RetrieveAnalyitcsAriaCounts";
			this.msdynmkt_ariacountsrequest = default(string);
			this.msdynmkt_appname = default(string);
			this.msdynmkt_primaryrecordid = default(string);
			this.msdynmkt_primaryrecordentityname = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdynmkt_RetrieveAnalyitcsAriaCounts")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_RetrieveAnalyitcsAriaCountsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdynmkt_RetrieveAnalyitcsAriaCountsResponse()
		{
		}
		
		public string msdynmkt_apiresponsedata
		{
			get
			{
				if (this.Results.Contains("msdynmkt_apiresponsedata"))
				{
					return ((string)(this.Results["msdynmkt_apiresponsedata"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdynmkt_error
		{
			get
			{
				if (this.Results.Contains("msdynmkt_error"))
				{
					return ((string)(this.Results["msdynmkt_error"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public int msdynmkt_resultcode
		{
			get
			{
				if (this.Results.Contains("msdynmkt_resultcode"))
				{
					return ((int)(this.Results["msdynmkt_resultcode"]));
				}
				else
				{
					return default(int);
				}
			}
		}
	}
}
#pragma warning restore CS1591
