#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdynmkt_PersonalizationDynamicTextAi")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_PersonalizationDynamicTextAiRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdynmkt_PersonalizationDynamicTextAiRequest
		{
			get
			{
				if (this.Parameters.Contains("msdynmkt_PersonalizationDynamicTextAiRequest"))
				{
					return ((string)(this.Parameters["msdynmkt_PersonalizationDynamicTextAiRequest"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdynmkt_PersonalizationDynamicTextAiRequest"] = value;
			}
		}
		
		public msdynmkt_PersonalizationDynamicTextAiRequest()
		{
			this.RequestName = "msdynmkt_PersonalizationDynamicTextAi";
			this.msdynmkt_PersonalizationDynamicTextAiRequest = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdynmkt_PersonalizationDynamicTextAi")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_PersonalizationDynamicTextAiResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdynmkt_PersonalizationDynamicTextAiResponse()
		{
		}
		
		public string msdynmkt_PersonalizationDynamicTextAiResponse
		{
			get
			{
				if (this.Results.Contains("msdynmkt_PersonalizationDynamicTextAiResponse"))
				{
					return ((string)(this.Results["msdynmkt_PersonalizationDynamicTextAiResponse"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
