#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_UpdateODOSFeatureEnabledRoles")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_UpdateODOSFeatureEnabledRolesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string FeatureName
		{
			get
			{
				if (this.Parameters.Contains("FeatureName"))
				{
					return ((string)(this.Parameters["FeatureName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["FeatureName"] = value;
			}
		}
		
		public string Roles
		{
			get
			{
				if (this.Parameters.Contains("Roles"))
				{
					return ((string)(this.Parameters["Roles"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Roles"] = value;
			}
		}
		
		public msdyn_UpdateODOSFeatureEnabledRolesRequest()
		{
			this.RequestName = "msdyn_UpdateODOSFeatureEnabledRoles";
			this.FeatureName = default(string);
			this.Roles = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_UpdateODOSFeatureEnabledRoles")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_UpdateODOSFeatureEnabledRolesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_UpdateODOSFeatureEnabledRolesResponse()
		{
		}
	}
}
#pragma warning restore CS1591
