#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_UpdateUserConsentBasedonSecurityRoles")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_UpdateUserConsentBasedonSecurityRolesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string SecurityRolesList
		{
			get
			{
				if (this.Parameters.Contains("SecurityRolesList"))
				{
					return ((string)(this.Parameters["SecurityRolesList"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SecurityRolesList"] = value;
			}
		}
		
		public msdyn_UpdateUserConsentBasedonSecurityRolesRequest()
		{
			this.RequestName = "msdyn_UpdateUserConsentBasedonSecurityRoles";
			this.SecurityRolesList = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_UpdateUserConsentBasedonSecurityRoles")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_UpdateUserConsentBasedonSecurityRolesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_UpdateUserConsentBasedonSecurityRolesResponse()
		{
		}
	}
}
#pragma warning restore CS1591
