#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SaveSalesCopilotEmailInsights")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SaveSalesCopilotEmailInsightsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_activityid
		{
			get
			{
				if (this.Parameters.Contains("msdyn_activityid"))
				{
					return ((string)(this.Parameters["msdyn_activityid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_activityid"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection msdyn_salescopilotemailinsights
		{
			get
			{
				if (this.Parameters.Contains("msdyn_salescopilotemailinsights"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["msdyn_salescopilotemailinsights"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["msdyn_salescopilotemailinsights"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection msdyn_extractedquestions
		{
			get
			{
				if (this.Parameters.Contains("msdyn_extractedquestions"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["msdyn_extractedquestions"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["msdyn_extractedquestions"] = value;
			}
		}
		
		public msdyn_SaveSalesCopilotEmailInsightsRequest()
		{
			this.RequestName = "msdyn_SaveSalesCopilotEmailInsights";
			this.msdyn_salescopilotemailinsights = default(Microsoft.Xrm.Sdk.EntityCollection);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SaveSalesCopilotEmailInsights")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SaveSalesCopilotEmailInsightsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_SaveSalesCopilotEmailInsightsResponse()
		{
		}
	}
}
#pragma warning restore CS1591
