#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_IoTCheckIfRecordExistsInEntity")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_IoTCheckIfRecordExistsInEntityRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string EntitiesLogicalNames
		{
			get
			{
				if (this.Parameters.Contains("EntitiesLogicalNames"))
				{
					return ((string)(this.Parameters["EntitiesLogicalNames"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntitiesLogicalNames"] = value;
			}
		}
		
		public msdyn_IoTCheckIfRecordExistsInEntityRequest()
		{
			this.RequestName = "msdyn_IoTCheckIfRecordExistsInEntity";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_IoTCheckIfRecordExistsInEntity")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_IoTCheckIfRecordExistsInEntityResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_IoTCheckIfRecordExistsInEntityResponse()
		{
		}
		
		public bool IsRecordExists
		{
			get
			{
				if (this.Results.Contains("IsRecordExists"))
				{
					return ((bool)(this.Results["IsRecordExists"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
}
#pragma warning restore CS1591
