#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_IntentServiceAPICallProxy")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_IntentServiceAPICallProxyRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string IntentServiceRequestPayload
		{
			get
			{
				if (this.Parameters.Contains("IntentServiceRequestPayload"))
				{
					return ((string)(this.Parameters["IntentServiceRequestPayload"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IntentServiceRequestPayload"] = value;
			}
		}
		
		public string IntentServiceRequestPayloadForTelemetry
		{
			get
			{
				if (this.Parameters.Contains("IntentServiceRequestPayloadForTelemetry"))
				{
					return ((string)(this.Parameters["IntentServiceRequestPayloadForTelemetry"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IntentServiceRequestPayloadForTelemetry"] = value;
			}
		}
		
		public string IntentServiceEntityType
		{
			get
			{
				if (this.Parameters.Contains("IntentServiceEntityType"))
				{
					return ((string)(this.Parameters["IntentServiceEntityType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IntentServiceEntityType"] = value;
			}
		}
		
		public msdyn_IntentServiceAPICallProxyRequest()
		{
			this.RequestName = "msdyn_IntentServiceAPICallProxy";
			this.IntentServiceRequestPayloadForTelemetry = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_IntentServiceAPICallProxy")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_IntentServiceAPICallProxyResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_IntentServiceAPICallProxyResponse()
		{
		}
		
		public string IntentServiceResponsePayload
		{
			get
			{
				if (this.Results.Contains("IntentServiceResponsePayload"))
				{
					return ((string)(this.Results["IntentServiceResponsePayload"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
