#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ExternalContextInitiateTranscriptUpload")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ExternalContextInitiateTranscriptUploadRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public string Transcript
		{
			get
			{
				if (this.Parameters.Contains("Transcript"))
				{
					return ((string)(this.Parameters["Transcript"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Transcript"] = value;
			}
		}
		
		public msdyn_ExternalContextInitiateTranscriptUploadRequest()
		{
			this.RequestName = "msdyn_ExternalContextInitiateTranscriptUpload";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
			this.Transcript = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ExternalContextInitiateTranscriptUpload")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ExternalContextInitiateTranscriptUploadResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ExternalContextInitiateTranscriptUploadResponse()
		{
		}
		
		public string[] BlockList
		{
			get
			{
				if (this.Results.Contains("BlockList"))
				{
					return ((string[])(this.Results["BlockList"]));
				}
				else
				{
					return default(string[]);
				}
			}
		}
		
		public string FileContinuationToken
		{
			get
			{
				if (this.Results.Contains("FileContinuationToken"))
				{
					return ((string)(this.Results["FileContinuationToken"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
