#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_cesinvoke")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_cesinvokeRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string CallType
		{
			get
			{
				if (this.Parameters.Contains("CallType"))
				{
					return ((string)(this.Parameters["CallType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CallType"] = value;
			}
		}
		
		public string EventName
		{
			get
			{
				if (this.Parameters.Contains("EventName"))
				{
					return ((string)(this.Parameters["EventName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EventName"] = value;
			}
		}
		
		public string SurveyName
		{
			get
			{
				if (this.Parameters.Contains("SurveyName"))
				{
					return ((string)(this.Parameters["SurveyName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SurveyName"] = value;
			}
		}
		
		public msdyn_cesinvokeRequest()
		{
			this.RequestName = "msdyn_cesinvoke";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_cesinvoke")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_cesinvokeResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_cesinvokeResponse()
		{
		}
		
		public string CESResult
		{
			get
			{
				if (this.Results.Contains("CESResult"))
				{
					return ((string)(this.Results["CESResult"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string IsSuccess
		{
			get
			{
				if (this.Results.Contains("IsSuccess"))
				{
					return ((string)(this.Results["IsSuccess"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
