#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_timetrackerapi")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_timetrackerapiRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string entityid
		{
			get
			{
				if (this.Parameters.Contains("entityid"))
				{
					return ((string)(this.Parameters["entityid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entityid"] = value;
			}
		}
		
		public string timeTrackerRecordId
		{
			get
			{
				if (this.Parameters.Contains("timeTrackerRecordId"))
				{
					return ((string)(this.Parameters["timeTrackerRecordId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["timeTrackerRecordId"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity timeTrackerRecord
		{
			get
			{
				if (this.Parameters.Contains("timeTrackerRecord"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["timeTrackerRecord"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Parameters["timeTrackerRecord"] = value;
			}
		}
		
		public string entitylogicalname
		{
			get
			{
				if (this.Parameters.Contains("entitylogicalname"))
				{
					return ((string)(this.Parameters["entitylogicalname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entitylogicalname"] = value;
			}
		}
		
		public msdyn_timetrackerapiRequest()
		{
			this.RequestName = "msdyn_timetrackerapi";
			this.entityid = default(string);
			this.entitylogicalname = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_timetrackerapi")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_timetrackerapiResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_timetrackerapiResponse()
		{
		}
		
		public string timetrackerjson
		{
			get
			{
				if (this.Results.Contains("timetrackerjson"))
				{
					return ((string)(this.Results["timetrackerjson"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
