#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetSalesCopilotConsentAndInfraStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetSalesCopilotConsentAndInfraStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_payload
		{
			get
			{
				if (this.Parameters.Contains("msdyn_payload"))
				{
					return ((string)(this.Parameters["msdyn_payload"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_payload"] = value;
			}
		}
		
		public msdyn_GetSalesCopilotConsentAndInfraStatusRequest()
		{
			this.RequestName = "msdyn_GetSalesCopilotConsentAndInfraStatus";
			this.msdyn_payload = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetSalesCopilotConsentAndInfraStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetSalesCopilotConsentAndInfraStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetSalesCopilotConsentAndInfraStatusResponse()
		{
		}
		
		public string msdyn_result
		{
			get
			{
				if (this.Results.Contains("msdyn_result"))
				{
					return ((string)(this.Results["msdyn_result"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
