#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SalesLeadSummary")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SalesLeadSummaryRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_additionalParams
		{
			get
			{
				if (this.Parameters.Contains("msdyn_additionalParams"))
				{
					return ((string)(this.Parameters["msdyn_additionalParams"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_additionalParams"] = value;
			}
		}
		
		public string msdyn_sessionId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_sessionId"))
				{
					return ((string)(this.Parameters["msdyn_sessionId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_sessionId"] = value;
			}
		}
		
		public string msdyn_activityId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_activityId"))
				{
					return ((string)(this.Parameters["msdyn_activityId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_activityId"] = value;
			}
		}
		
		public string msdyn_parentContactId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_parentContactId"))
				{
					return ((string)(this.Parameters["msdyn_parentContactId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_parentContactId"] = value;
			}
		}
		
		public string msdyn_parentAccountId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_parentAccountId"))
				{
					return ((string)(this.Parameters["msdyn_parentAccountId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_parentAccountId"] = value;
			}
		}
		
		public string msdyn_responseFormat
		{
			get
			{
				if (this.Parameters.Contains("msdyn_responseFormat"))
				{
					return ((string)(this.Parameters["msdyn_responseFormat"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_responseFormat"] = value;
			}
		}
		
		public bool msdyn_isMergedCatchupAndSummary
		{
			get
			{
				if (this.Parameters.Contains("msdyn_isMergedCatchupAndSummary"))
				{
					return ((bool)(this.Parameters["msdyn_isMergedCatchupAndSummary"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["msdyn_isMergedCatchupAndSummary"] = value;
			}
		}
		
		public string msdyn_skipHeader
		{
			get
			{
				if (this.Parameters.Contains("msdyn_skipHeader"))
				{
					return ((string)(this.Parameters["msdyn_skipHeader"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_skipHeader"] = value;
			}
		}
		
		public string msdyn_id
		{
			get
			{
				if (this.Parameters.Contains("msdyn_id"))
				{
					return ((string)(this.Parameters["msdyn_id"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_id"] = value;
			}
		}
		
		public System.DateTime msdyn_lastComputationTime
		{
			get
			{
				if (this.Parameters.Contains("msdyn_lastComputationTime"))
				{
					return ((System.DateTime)(this.Parameters["msdyn_lastComputationTime"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["msdyn_lastComputationTime"] = value;
			}
		}
		
		public bool msdyn_doSuggestUpdates
		{
			get
			{
				if (this.Parameters.Contains("msdyn_doSuggestUpdates"))
				{
					return ((bool)(this.Parameters["msdyn_doSuggestUpdates"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["msdyn_doSuggestUpdates"] = value;
			}
		}
		
		public msdyn_SalesLeadSummaryRequest()
		{
			this.RequestName = "msdyn_SalesLeadSummary";
			this.msdyn_id = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SalesLeadSummary")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SalesLeadSummaryResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_SalesLeadSummaryResponse()
		{
		}
		
		public string msdyn_additionalDetails
		{
			get
			{
				if (this.Results.Contains("msdyn_additionalDetails"))
				{
					return ((string)(this.Results["msdyn_additionalDetails"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public bool msdyn_canUseCache
		{
			get
			{
				if (this.Results.Contains("msdyn_canUseCache"))
				{
					return ((bool)(this.Results["msdyn_canUseCache"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
		
		public string msdyn_sales_copilot_output
		{
			get
			{
				if (this.Results.Contains("msdyn_sales_copilot_output"))
				{
					return ((string)(this.Results["msdyn_sales_copilot_output"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdyn_summary
		{
			get
			{
				if (this.Results.Contains("msdyn_summary"))
				{
					return ((string)(this.Results["msdyn_summary"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdyn_summary_raw
		{
			get
			{
				if (this.Results.Contains("msdyn_summary_raw"))
				{
					return ((string)(this.Results["msdyn_summary_raw"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdyn_version
		{
			get
			{
				if (this.Results.Contains("msdyn_version"))
				{
					return ((string)(this.Results["msdyn_version"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
