#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ExecuteSIRequest")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ExecuteSIRequestRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string MethodName
		{
			get
			{
				if (this.Parameters.Contains("MethodName"))
				{
					return ((string)(this.Parameters["MethodName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["MethodName"] = value;
			}
		}
		
		public string MethodParams
		{
			get
			{
				if (this.Parameters.Contains("MethodParams"))
				{
					return ((string)(this.Parameters["MethodParams"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["MethodParams"] = value;
			}
		}
		
		public string HttpRequestType
		{
			get
			{
				if (this.Parameters.Contains("HttpRequestType"))
				{
					return ((string)(this.Parameters["HttpRequestType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["HttpRequestType"] = value;
			}
		}
		
		public bool OrgMigratedToCoreServices
		{
			get
			{
				if (this.Parameters.Contains("OrgMigratedToCoreServices"))
				{
					return ((bool)(this.Parameters["OrgMigratedToCoreServices"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["OrgMigratedToCoreServices"] = value;
			}
		}
		
		public msdyn_ExecuteSIRequestRequest()
		{
			this.RequestName = "msdyn_ExecuteSIRequest";
			this.MethodName = default(string);
			this.HttpRequestType = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ExecuteSIRequest")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ExecuteSIRequestResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ExecuteSIRequestResponse()
		{
		}
		
		public string Response
		{
			get
			{
				if (this.Results.Contains("Response"))
				{
					return ((string)(this.Results["Response"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
