#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetBoolFCSValue")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetBoolFCSValueRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_BoolFCSKey
		{
			get
			{
				if (this.Parameters.Contains("msdyn_BoolFCSKey"))
				{
					return ((string)(this.Parameters["msdyn_BoolFCSKey"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_BoolFCSKey"] = value;
			}
		}
		
		public string msdyn_BoolFCSNamespace
		{
			get
			{
				if (this.Parameters.Contains("msdyn_BoolFCSNamespace"))
				{
					return ((string)(this.Parameters["msdyn_BoolFCSNamespace"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_BoolFCSNamespace"] = value;
			}
		}
		
		public msdyn_GetBoolFCSValueRequest()
		{
			this.RequestName = "msdyn_GetBoolFCSValue";
			this.msdyn_BoolFCSKey = default(string);
			this.msdyn_BoolFCSNamespace = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetBoolFCSValue")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetBoolFCSValueResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetBoolFCSValueResponse()
		{
		}
		
		public string msdyn_BoolFCSValue
		{
			get
			{
				if (this.Results.Contains("msdyn_BoolFCSValue"))
				{
					return ((string)(this.Results["msdyn_BoolFCSValue"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
