#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_StartODOSProvisioning")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_StartODOSProvisioningRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string Entities
		{
			get
			{
				if (this.Parameters.Contains("Entities"))
				{
					return ((string)(this.Parameters["Entities"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Entities"] = value;
			}
		}
		
		public string FeatureName
		{
			get
			{
				if (this.Parameters.Contains("FeatureName"))
				{
					return ((string)(this.Parameters["FeatureName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["FeatureName"] = value;
			}
		}
		
		public string FeatureDisplayName
		{
			get
			{
				if (this.Parameters.Contains("FeatureDisplayName"))
				{
					return ((string)(this.Parameters["FeatureDisplayName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["FeatureDisplayName"] = value;
			}
		}
		
		public string Roles
		{
			get
			{
				if (this.Parameters.Contains("Roles"))
				{
					return ((string)(this.Parameters["Roles"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Roles"] = value;
			}
		}
		
		public string Primitives
		{
			get
			{
				if (this.Parameters.Contains("Primitives"))
				{
					return ((string)(this.Parameters["Primitives"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Primitives"] = value;
			}
		}
		
		public msdyn_StartODOSProvisioningRequest()
		{
			this.RequestName = "msdyn_StartODOSProvisioning";
			this.Entities = default(string);
			this.FeatureName = default(string);
			this.FeatureDisplayName = default(string);
			this.Roles = default(string);
			this.Primitives = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_StartODOSProvisioning")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_StartODOSProvisioningResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_StartODOSProvisioningResponse()
		{
		}
	}
}
#pragma warning restore CS1591
