#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_assignentity")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_assignentityRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string RegardingEntityId
		{
			get
			{
				if (this.Parameters.Contains("RegardingEntityId"))
				{
					return ((string)(this.Parameters["RegardingEntityId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RegardingEntityId"] = value;
			}
		}
		
		public string RegardingEntityName
		{
			get
			{
				if (this.Parameters.Contains("RegardingEntityName"))
				{
					return ((string)(this.Parameters["RegardingEntityName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RegardingEntityName"] = value;
			}
		}
		
		public string SegmentId
		{
			get
			{
				if (this.Parameters.Contains("SegmentId"))
				{
					return ((string)(this.Parameters["SegmentId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SegmentId"] = value;
			}
		}
		
		public string CorrelationId
		{
			get
			{
				if (this.Parameters.Contains("CorrelationId"))
				{
					return ((string)(this.Parameters["CorrelationId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CorrelationId"] = value;
			}
		}
		
		public msdyn_assignentityRequest()
		{
			this.RequestName = "msdyn_assignentity";
			this.RegardingEntityId = default(string);
			this.RegardingEntityName = default(string);
			this.SegmentId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_assignentity")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_assignentityResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_assignentityResponse()
		{
		}
	}
}
#pragma warning restore CS1591
