#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_FindRulesetDependencies")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_FindRulesetDependenciesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference InputEntityReference
		{
			get
			{
				if (this.Parameters.Contains("InputEntityReference"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["InputEntityReference"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["InputEntityReference"] = value;
			}
		}
		
		public msdyn_FindRulesetDependenciesRequest()
		{
			this.RequestName = "msdyn_FindRulesetDependencies";
			this.InputEntityReference = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_FindRulesetDependencies")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_FindRulesetDependenciesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_FindRulesetDependenciesResponse()
		{
		}
		
		public string DependenciesJson
		{
			get
			{
				if (this.Results.Contains("DependenciesJson"))
				{
					return ((string)(this.Results["DependenciesJson"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
