#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_MigrateArc")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_MigrateArcRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string ArcMigrationRequest
		{
			get
			{
				if (this.Parameters.Contains("ArcMigrationRequest"))
				{
					return ((string)(this.Parameters["ArcMigrationRequest"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ArcMigrationRequest"] = value;
			}
		}
		
		public msdyn_MigrateArcRequest()
		{
			this.RequestName = "msdyn_MigrateArc";
			this.ArcMigrationRequest = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_MigrateArc")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_MigrateArcResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_MigrateArcResponse()
		{
		}
		
		public string Exception
		{
			get
			{
				if (this.Results.Contains("Exception"))
				{
					return ((string)(this.Results["Exception"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string OutputString
		{
			get
			{
				if (this.Results.Contains("OutputString"))
				{
					return ((string)(this.Results["OutputString"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
