#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_IoTGetDeviceEvents")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_IoTGetDeviceEventsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string IotDeviceId
		{
			get
			{
				if (this.Parameters.Contains("IotDeviceId"))
				{
					return ((string)(this.Parameters["IotDeviceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IotDeviceId"] = value;
			}
		}
		
		public System.DateTime From
		{
			get
			{
				if (this.Parameters.Contains("From"))
				{
					return ((System.DateTime)(this.Parameters["From"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["From"] = value;
			}
		}
		
		public System.DateTime To
		{
			get
			{
				if (this.Parameters.Contains("To"))
				{
					return ((System.DateTime)(this.Parameters["To"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["To"] = value;
			}
		}
		
		public msdyn_IoTGetDeviceEventsRequest()
		{
			this.RequestName = "msdyn_IoTGetDeviceEvents";
			this.IotDeviceId = default(string);
			this.From = default(System.DateTime);
			this.To = default(System.DateTime);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_IoTGetDeviceEvents")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_IoTGetDeviceEventsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_IoTGetDeviceEventsResponse()
		{
		}
		
		public string EventsData
		{
			get
			{
				if (this.Results.Contains("EventsData"))
				{
					return ((string)(this.Results["EventsData"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
