#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdynmkt_ChannelContentPersonalize")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_ChannelContentPersonalizeRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdynmkt_PersonalizeContentRequest
		{
			get
			{
				if (this.Parameters.Contains("msdynmkt_PersonalizeContentRequest"))
				{
					return ((string)(this.Parameters["msdynmkt_PersonalizeContentRequest"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdynmkt_PersonalizeContentRequest"] = value;
			}
		}
		
		public msdynmkt_ChannelContentPersonalizeRequest()
		{
			this.RequestName = "msdynmkt_ChannelContentPersonalize";
			this.msdynmkt_PersonalizeContentRequest = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdynmkt_ChannelContentPersonalize")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_ChannelContentPersonalizeResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdynmkt_ChannelContentPersonalizeResponse()
		{
		}
		
		public string msdynmkt_PersonalizeContentResponse
		{
			get
			{
				if (this.Results.Contains("msdynmkt_PersonalizeContentResponse"))
				{
					return ((string)(this.Results["msdynmkt_PersonalizeContentResponse"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
