#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_BulkAITestCaseUpload")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_BulkAITestCaseUploadRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string request
		{
			get
			{
				if (this.Parameters.Contains("request"))
				{
					return ((string)(this.Parameters["request"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["request"] = value;
			}
		}
		
		public msdyn_BulkAITestCaseUploadRequest()
		{
			this.RequestName = "msdyn_BulkAITestCaseUpload";
			this.request = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_BulkAITestCaseUpload")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_BulkAITestCaseUploadResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_BulkAITestCaseUploadResponse()
		{
		}
		
		public string response
		{
			get
			{
				if (this.Results.Contains("response"))
				{
					return ((string)(this.Results["response"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
