#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_RetrieveKPIValuesForGDPR")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_RetrieveKPIValuesForGDPRRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference CRMRecord
		{
			get
			{
				if (this.Parameters.Contains("CRMRecord"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["CRMRecord"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["CRMRecord"] = value;
			}
		}
		
		public msdyn_RetrieveKPIValuesForGDPRRequest()
		{
			this.RequestName = "msdyn_RetrieveKPIValuesForGDPR";
			this.CRMRecord = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_RetrieveKPIValuesForGDPR")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_RetrieveKPIValuesForGDPRResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_RetrieveKPIValuesForGDPRResponse()
		{
		}
		
		public string Response
		{
			get
			{
				if (this.Results.Contains("Response"))
				{
					return ((string)(this.Results["Response"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
