#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SalesAcceleratorMailNotificationToAdmin")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SalesAcceleratorMailNotificationToAdminRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string InputData
		{
			get
			{
				if (this.Parameters.Contains("InputData"))
				{
					return ((string)(this.Parameters["InputData"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["InputData"] = value;
			}
		}
		
		public msdyn_SalesAcceleratorMailNotificationToAdminRequest()
		{
			this.RequestName = "msdyn_SalesAcceleratorMailNotificationToAdmin";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SalesAcceleratorMailNotificationToAdmin")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SalesAcceleratorMailNotificationToAdminResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_SalesAcceleratorMailNotificationToAdminResponse()
		{
		}
	}
}
#pragma warning restore CS1591
