#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_DuplicateDetectionTriggerAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_DuplicateDetectionTriggerActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string BaseRecordType
		{
			get
			{
				if (this.Parameters.Contains("BaseRecordType"))
				{
					return ((string)(this.Parameters["BaseRecordType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BaseRecordType"] = value;
			}
		}
		
		public string BaseRecordId
		{
			get
			{
				if (this.Parameters.Contains("BaseRecordId"))
				{
					return ((string)(this.Parameters["BaseRecordId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["BaseRecordId"] = value;
			}
		}
		
		public msdyn_DuplicateDetectionTriggerActionRequest()
		{
			this.RequestName = "msdyn_DuplicateDetectionTriggerAction";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_DuplicateDetectionTriggerAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_DuplicateDetectionTriggerActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_DuplicateDetectionTriggerActionResponse()
		{
		}
	}
}
#pragma warning restore CS1591
