#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_MigrateSla")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_MigrateSlaRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string SlaMigrationRequest
		{
			get
			{
				if (this.Parameters.Contains("SlaMigrationRequest"))
				{
					return ((string)(this.Parameters["SlaMigrationRequest"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SlaMigrationRequest"] = value;
			}
		}
		
		public msdyn_MigrateSlaRequest()
		{
			this.RequestName = "msdyn_MigrateSla";
			this.SlaMigrationRequest = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_MigrateSla")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_MigrateSlaResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_MigrateSlaResponse()
		{
		}
		
		public string Exception
		{
			get
			{
				if (this.Results.Contains("Exception"))
				{
					return ((string)(this.Results["Exception"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string OutputString
		{
			get
			{
				if (this.Results.Contains("OutputString"))
				{
					return ((string)(this.Results["OutputString"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
