#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdynmkt/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdynmkt_PersonalizationGetEntityAttributes")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_PersonalizationGetEntityAttributesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string GetEntityAttributesRequest
		{
			get
			{
				if (this.Parameters.Contains("GetEntityAttributesRequest"))
				{
					return ((string)(this.Parameters["GetEntityAttributesRequest"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["GetEntityAttributesRequest"] = value;
			}
		}
		
		public msdynmkt_PersonalizationGetEntityAttributesRequest()
		{
			this.RequestName = "msdynmkt_PersonalizationGetEntityAttributes";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdynmkt/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdynmkt_PersonalizationGetEntityAttributes")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdynmkt_PersonalizationGetEntityAttributesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdynmkt_PersonalizationGetEntityAttributesResponse()
		{
		}
		
		public string GetEntityAttributesResult
		{
			get
			{
				if (this.Results.Contains("GetEntityAttributesResult"))
				{
					return ((string)(this.Results["GetEntityAttributesResult"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
