#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetRIProvisioningStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetRIProvisioningStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public msdyn_GetRIProvisioningStatusRequest()
		{
			this.RequestName = "msdyn_GetRIProvisioningStatus";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetRIProvisioningStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetRIProvisioningStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetRIProvisioningStatusResponse()
		{
		}
		
		public string DCIHubPlanType
		{
			get
			{
				if (this.Results.Contains("DCIHubPlanType"))
				{
					return ((string)(this.Results["DCIHubPlanType"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public int EEProvisioningStatus
		{
			get
			{
				if (this.Results.Contains("EEProvisioningStatus"))
				{
					return ((int)(this.Results["EEProvisioningStatus"]));
				}
				else
				{
					return default(int);
				}
			}
		}
		
		public string RIErrorStatusCode
		{
			get
			{
				if (this.Results.Contains("RIErrorStatusCode"))
				{
					return ((string)(this.Results["RIErrorStatusCode"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string RIErrorStatusMessage
		{
			get
			{
				if (this.Results.Contains("RIErrorStatusMessage"))
				{
					return ((string)(this.Results["RIErrorStatusMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public int RIProvisioningStatus
		{
			get
			{
				if (this.Results.Contains("RIProvisioningStatus"))
				{
					return ((int)(this.Results["RIProvisioningStatus"]));
				}
				else
				{
					return default(int);
				}
			}
		}
	}
}
#pragma warning restore CS1591
