#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_InitEntityRoutingFlow")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_InitEntityRoutingFlowRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string LiveWorkStreamId
		{
			get
			{
				if (this.Parameters.Contains("LiveWorkStreamId"))
				{
					return ((string)(this.Parameters["LiveWorkStreamId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["LiveWorkStreamId"] = value;
			}
		}
		
		public string QueueId
		{
			get
			{
				if (this.Parameters.Contains("QueueId"))
				{
					return ((string)(this.Parameters["QueueId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["QueueId"] = value;
			}
		}
		
		public string EntityRecordId
		{
			get
			{
				if (this.Parameters.Contains("EntityRecordId"))
				{
					return ((string)(this.Parameters["EntityRecordId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityRecordId"] = value;
			}
		}
		
		public string EntityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("EntityLogicalName"))
				{
					return ((string)(this.Parameters["EntityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntityLogicalName"] = value;
			}
		}
		
		public string LiveWorkItemTitle
		{
			get
			{
				if (this.Parameters.Contains("LiveWorkItemTitle"))
				{
					return ((string)(this.Parameters["LiveWorkItemTitle"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["LiveWorkItemTitle"] = value;
			}
		}
		
		public msdyn_InitEntityRoutingFlowRequest()
		{
			this.RequestName = "msdyn_InitEntityRoutingFlow";
			this.LiveWorkStreamId = default(string);
			this.EntityRecordId = default(string);
			this.EntityLogicalName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_InitEntityRoutingFlow")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_InitEntityRoutingFlowResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_InitEntityRoutingFlowResponse()
		{
		}
	}
}
#pragma warning restore CS1591
