#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_OnNewActivityForARCRecord")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_OnNewActivityForARCRecordRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference msdyn_primaryEntityReference
		{
			get
			{
				if (this.Parameters.Contains("msdyn_primaryEntityReference"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["msdyn_primaryEntityReference"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["msdyn_primaryEntityReference"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference msdyn_sourceEntityReference
		{
			get
			{
				if (this.Parameters.Contains("msdyn_sourceEntityReference"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["msdyn_sourceEntityReference"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["msdyn_sourceEntityReference"] = value;
			}
		}
		
		public msdyn_OnNewActivityForARCRecordRequest()
		{
			this.RequestName = "msdyn_OnNewActivityForARCRecord";
			this.msdyn_primaryEntityReference = default(Microsoft.Xrm.Sdk.EntityReference);
			this.msdyn_sourceEntityReference = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_OnNewActivityForARCRecord")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_OnNewActivityForARCRecordResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_OnNewActivityForARCRecordResponse()
		{
		}
	}
}
#pragma warning restore CS1591
