#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetExtractsFromContent")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetExtractsFromContentRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_keywords
		{
			get
			{
				if (this.Parameters.Contains("msdyn_keywords"))
				{
					return ((string)(this.Parameters["msdyn_keywords"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_keywords"] = value;
			}
		}
		
		public string msdyn_activityId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_activityId"))
				{
					return ((string)(this.Parameters["msdyn_activityId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_activityId"] = value;
			}
		}
		
		public string msdyn_userQuery
		{
			get
			{
				if (this.Parameters.Contains("msdyn_userQuery"))
				{
					return ((string)(this.Parameters["msdyn_userQuery"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_userQuery"] = value;
			}
		}
		
		public string msdyn_extractOperationInputParams
		{
			get
			{
				if (this.Parameters.Contains("msdyn_extractOperationInputParams"))
				{
					return ((string)(this.Parameters["msdyn_extractOperationInputParams"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_extractOperationInputParams"] = value;
			}
		}
		
		public string msdyn_source
		{
			get
			{
				if (this.Parameters.Contains("msdyn_source"))
				{
					return ((string)(this.Parameters["msdyn_source"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_source"] = value;
			}
		}
		
		public int msdyn_top
		{
			get
			{
				if (this.Parameters.Contains("msdyn_top"))
				{
					return ((int)(this.Parameters["msdyn_top"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["msdyn_top"] = value;
			}
		}
		
		public msdyn_GetExtractsFromContentRequest()
		{
			this.RequestName = "msdyn_GetExtractsFromContent";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetExtractsFromContent")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetExtractsFromContentResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetExtractsFromContentResponse()
		{
		}
		
		public string msdyn_documents
		{
			get
			{
				if (this.Results.Contains("msdyn_documents"))
				{
					return ((string)(this.Results["msdyn_documents"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdyn_mdlDetails
		{
			get
			{
				if (this.Results.Contains("msdyn_mdlDetails"))
				{
					return ((string)(this.Results["msdyn_mdlDetails"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
