#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetEntityLinkChatConfiguration")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetEntityLinkChatConfigurationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_RegardingEntityName
		{
			get
			{
				if (this.Parameters.Contains("msdyn_RegardingEntityName"))
				{
					return ((string)(this.Parameters["msdyn_RegardingEntityName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_RegardingEntityName"] = value;
			}
		}
		
		public msdyn_GetEntityLinkChatConfigurationRequest()
		{
			this.RequestName = "msdyn_GetEntityLinkChatConfiguration";
			this.msdyn_RegardingEntityName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetEntityLinkChatConfiguration")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetEntityLinkChatConfigurationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetEntityLinkChatConfigurationResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity msdyn_EntityLinkChatConfig
		{
			get
			{
				if (this.Results.Contains("msdyn_EntityLinkChatConfig"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["msdyn_EntityLinkChatConfig"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
		}
	}
}
#pragma warning restore CS1591
