#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_D365ChannelsNotification")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_D365ChannelsNotificationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string notificationPayLoad
		{
			get
			{
				if (this.Parameters.Contains("notificationPayLoad"))
				{
					return ((string)(this.Parameters["notificationPayLoad"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["notificationPayLoad"] = value;
			}
		}
		
		public msdyn_D365ChannelsNotificationRequest()
		{
			this.RequestName = "msdyn_D365ChannelsNotification";
			this.notificationPayLoad = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_D365ChannelsNotification")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_D365ChannelsNotificationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_D365ChannelsNotificationResponse()
		{
		}
		
		public string responseMessage
		{
			get
			{
				if (this.Results.Contains("responseMessage"))
				{
					return ((string)(this.Results["responseMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
