#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_UpgradeTelemetry")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_UpgradeTelemetryRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public int EventId
		{
			get
			{
				if (this.Parameters.Contains("EventId"))
				{
					return ((int)(this.Parameters["EventId"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["EventId"] = value;
			}
		}
		
		public string RunId
		{
			get
			{
				if (this.Parameters.Contains("RunId"))
				{
					return ((string)(this.Parameters["RunId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RunId"] = value;
			}
		}
		
		public string PackageName
		{
			get
			{
				if (this.Parameters.Contains("PackageName"))
				{
					return ((string)(this.Parameters["PackageName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PackageName"] = value;
			}
		}
		
		public string SolutionName
		{
			get
			{
				if (this.Parameters.Contains("SolutionName"))
				{
					return ((string)(this.Parameters["SolutionName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SolutionName"] = value;
			}
		}
		
		public string StartingVersion
		{
			get
			{
				if (this.Parameters.Contains("StartingVersion"))
				{
					return ((string)(this.Parameters["StartingVersion"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["StartingVersion"] = value;
			}
		}
		
		public string TargetVersion
		{
			get
			{
				if (this.Parameters.Contains("TargetVersion"))
				{
					return ((string)(this.Parameters["TargetVersion"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["TargetVersion"] = value;
			}
		}
		
		public int DurationSeconds
		{
			get
			{
				if (this.Parameters.Contains("DurationSeconds"))
				{
					return ((int)(this.Parameters["DurationSeconds"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["DurationSeconds"] = value;
			}
		}
		
		public int Success
		{
			get
			{
				if (this.Parameters.Contains("Success"))
				{
					return ((int)(this.Parameters["Success"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["Success"] = value;
			}
		}
		
		public string StepId
		{
			get
			{
				if (this.Parameters.Contains("StepId"))
				{
					return ((string)(this.Parameters["StepId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["StepId"] = value;
			}
		}
		
		public string StepName
		{
			get
			{
				if (this.Parameters.Contains("StepName"))
				{
					return ((string)(this.Parameters["StepName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["StepName"] = value;
			}
		}
		
		public string ErrorMessage
		{
			get
			{
				if (this.Parameters.Contains("ErrorMessage"))
				{
					return ((string)(this.Parameters["ErrorMessage"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ErrorMessage"] = value;
			}
		}
		
		public string Details
		{
			get
			{
				if (this.Parameters.Contains("Details"))
				{
					return ((string)(this.Parameters["Details"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Details"] = value;
			}
		}
		
		public msdyn_UpgradeTelemetryRequest()
		{
			this.RequestName = "msdyn_UpgradeTelemetry";
			this.EventId = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_UpgradeTelemetry")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_UpgradeTelemetryResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_UpgradeTelemetryResponse()
		{
		}
		
		public string output
		{
			get
			{
				if (this.Results.Contains("output"))
				{
					return ((string)(this.Results["output"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
