#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_UpdateAuditState")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_UpdateAuditStateRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_input
		{
			get
			{
				if (this.Parameters.Contains("msdyn_input"))
				{
					return ((string)(this.Parameters["msdyn_input"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_input"] = value;
			}
		}
		
		public msdyn_UpdateAuditStateRequest()
		{
			this.RequestName = "msdyn_UpdateAuditState";
			this.msdyn_input = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_UpdateAuditState")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_UpdateAuditStateResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_UpdateAuditStateResponse()
		{
		}
	}
}
#pragma warning restore CS1591
