#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SalesRoutingIdentifyAttributes")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SalesRoutingIdentifyAttributesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public msdyn_SalesRoutingIdentifyAttributesRequest()
		{
			this.RequestName = "msdyn_SalesRoutingIdentifyAttributes";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SalesRoutingIdentifyAttributes")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SalesRoutingIdentifyAttributesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_SalesRoutingIdentifyAttributesResponse()
		{
		}
		
		public string JobId
		{
			get
			{
				if (this.Results.Contains("JobId"))
				{
					return ((string)(this.Results["JobId"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public bool JobStatus
		{
			get
			{
				if (this.Results.Contains("JobStatus"))
				{
					return ((bool)(this.Results["JobStatus"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
}
#pragma warning restore CS1591
