#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_CheckForDuplicatesAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_CheckForDuplicatesActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.Entity Record
		{
			get
			{
				if (this.Parameters.Contains("Record"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["Record"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Parameters["Record"] = value;
			}
		}
		
		public msdyn_CheckForDuplicatesActionRequest()
		{
			this.RequestName = "msdyn_CheckForDuplicatesAction";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_CheckForDuplicatesAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_CheckForDuplicatesActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_CheckForDuplicatesActionResponse()
		{
		}
		
		public int DuplicateRecordCount
		{
			get
			{
				if (this.Results.Contains("DuplicateRecordCount"))
				{
					return ((int)(this.Results["DuplicateRecordCount"]));
				}
				else
				{
					return default(int);
				}
			}
		}
		
		public bool IsDuplicateDetectionEnabled
		{
			get
			{
				if (this.Results.Contains("IsDuplicateDetectionEnabled"))
				{
					return ((bool)(this.Results["IsDuplicateDetectionEnabled"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
}
#pragma warning restore CS1591
