#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_DeprovisionUnifiedRouting")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_DeprovisionUnifiedRoutingRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public msdyn_DeprovisionUnifiedRoutingRequest()
		{
			this.RequestName = "msdyn_DeprovisionUnifiedRouting";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_DeprovisionUnifiedRouting")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_DeprovisionUnifiedRoutingResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_DeprovisionUnifiedRoutingResponse()
		{
		}
		
		public string msdyn_customMessage
		{
			get
			{
				if (this.Results.Contains("msdyn_customMessage"))
				{
					return ((string)(this.Results["msdyn_customMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdyn_errorCode
		{
			get
			{
				if (this.Results.Contains("msdyn_errorCode"))
				{
					return ((string)(this.Results["msdyn_errorCode"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdyn_responseCode
		{
			get
			{
				if (this.Results.Contains("msdyn_responseCode"))
				{
					return ((string)(this.Results["msdyn_responseCode"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdyn_serviceRequestId
		{
			get
			{
				if (this.Results.Contains("msdyn_serviceRequestId"))
				{
					return ((string)(this.Results["msdyn_serviceRequestId"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
