#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_TrackExchangeActivity")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_TrackExchangeActivityRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string ExchangeItemId
		{
			get
			{
				if (this.Parameters.Contains("ExchangeItemId"))
				{
					return ((string)(this.Parameters["ExchangeItemId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ExchangeItemId"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Regarding
		{
			get
			{
				if (this.Parameters.Contains("Regarding"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Regarding"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Regarding"] = value;
			}
		}
		
		public string EntitySetName
		{
			get
			{
				if (this.Parameters.Contains("EntitySetName"))
				{
					return ((string)(this.Parameters["EntitySetName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["EntitySetName"] = value;
			}
		}
		
		public msdyn_TrackExchangeActivityRequest()
		{
			this.RequestName = "msdyn_TrackExchangeActivity";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_TrackExchangeActivity")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_TrackExchangeActivityResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_TrackExchangeActivityResponse()
		{
		}
		
		public string ExchangeResponse
		{
			get
			{
				if (this.Results.Contains("ExchangeResponse"))
				{
					return ((string)(this.Results["ExchangeResponse"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
