#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetCustomActionParameters")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetCustomActionParametersRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public System.Guid workflowId
		{
			get
			{
				if (this.Parameters.Contains("workflowId"))
				{
					return ((System.Guid)(this.Parameters["workflowId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["workflowId"] = value;
			}
		}
		
		public System.Guid correlationId
		{
			get
			{
				if (this.Parameters.Contains("correlationId"))
				{
					return ((System.Guid)(this.Parameters["correlationId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["correlationId"] = value;
			}
		}
		
		public string customAction
		{
			get
			{
				if (this.Parameters.Contains("customAction"))
				{
					return ((string)(this.Parameters["customAction"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["customAction"] = value;
			}
		}
		
		public msdyn_GetCustomActionParametersRequest()
		{
			this.RequestName = "msdyn_GetCustomActionParameters";
			this.workflowId = default(System.Guid);
			this.correlationId = default(System.Guid);
			this.customAction = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetCustomActionParameters")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetCustomActionParametersResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetCustomActionParametersResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Entity customActionsParams
		{
			get
			{
				if (this.Results.Contains("customActionsParams"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["customActionsParams"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
		}
		
		public string dynamicSchema
		{
			get
			{
				if (this.Results.Contains("dynamicSchema"))
				{
					return ((string)(this.Results["dynamicSchema"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
