#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ResetWorkDistributionFlow")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ResetWorkDistributionFlowRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public bool ShouldMaintainCustomizations
		{
			get
			{
				if (this.Parameters.Contains("ShouldMaintainCustomizations"))
				{
					return ((bool)(this.Parameters["ShouldMaintainCustomizations"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["ShouldMaintainCustomizations"] = value;
			}
		}
		
		public msdyn_ResetWorkDistributionFlowRequest()
		{
			this.RequestName = "msdyn_ResetWorkDistributionFlow";
			this.ShouldMaintainCustomizations = default(bool);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ResetWorkDistributionFlow")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ResetWorkDistributionFlowResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ResetWorkDistributionFlowResponse()
		{
		}
	}
}
#pragma warning restore CS1591
