#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_editSalesSequenceExperimentStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_editSalesSequenceExperimentStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_winnerOrDefault
		{
			get
			{
				if (this.Parameters.Contains("msdyn_winnerOrDefault"))
				{
					return ((string)(this.Parameters["msdyn_winnerOrDefault"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_winnerOrDefault"] = value;
			}
		}
		
		public string msdyn_experimentKey
		{
			get
			{
				if (this.Parameters.Contains("msdyn_experimentKey"))
				{
					return ((string)(this.Parameters["msdyn_experimentKey"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_experimentKey"] = value;
			}
		}
		
		public string msdyn_expiryTime
		{
			get
			{
				if (this.Parameters.Contains("msdyn_expiryTime"))
				{
					return ((string)(this.Parameters["msdyn_expiryTime"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_expiryTime"] = value;
			}
		}
		
		public string msdyn_experimentVersionRecordId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_experimentVersionRecordId"))
				{
					return ((string)(this.Parameters["msdyn_experimentVersionRecordId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_experimentVersionRecordId"] = value;
			}
		}
		
		public bool msdyn_isDeactivated
		{
			get
			{
				if (this.Parameters.Contains("msdyn_isDeactivated"))
				{
					return ((bool)(this.Parameters["msdyn_isDeactivated"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["msdyn_isDeactivated"] = value;
			}
		}
		
		public msdyn_editSalesSequenceExperimentStatusRequest()
		{
			this.RequestName = "msdyn_editSalesSequenceExperimentStatus";
			this.msdyn_winnerOrDefault = default(string);
			this.msdyn_experimentKey = default(string);
			this.msdyn_experimentVersionRecordId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_editSalesSequenceExperimentStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_editSalesSequenceExperimentStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_editSalesSequenceExperimentStatusResponse()
		{
		}
		
		public string msdyn_editExperimentStatusResponse
		{
			get
			{
				if (this.Results.Contains("msdyn_editExperimentStatusResponse"))
				{
					return ((string)(this.Results["msdyn_editExperimentStatusResponse"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
