#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetSankeyData")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetSankeyDataRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public System.DateTime msdyn_datefrom
		{
			get
			{
				if (this.Parameters.Contains("msdyn_datefrom"))
				{
					return ((System.DateTime)(this.Parameters["msdyn_datefrom"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["msdyn_datefrom"] = value;
			}
		}
		
		public string msdyn_sequenceid
		{
			get
			{
				if (this.Parameters.Contains("msdyn_sequenceid"))
				{
					return ((string)(this.Parameters["msdyn_sequenceid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_sequenceid"] = value;
			}
		}
		
		public System.DateTime msdyn_dateto
		{
			get
			{
				if (this.Parameters.Contains("msdyn_dateto"))
				{
					return ((System.DateTime)(this.Parameters["msdyn_dateto"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["msdyn_dateto"] = value;
			}
		}
		
		public msdyn_GetSankeyDataRequest()
		{
			this.RequestName = "msdyn_GetSankeyData";
			this.msdyn_datefrom = default(System.DateTime);
			this.msdyn_sequenceid = default(string);
			this.msdyn_dateto = default(System.DateTime);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetSankeyData")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetSankeyDataResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetSankeyDataResponse()
		{
		}
		
		public string msdyn_response
		{
			get
			{
				if (this.Results.Contains("msdyn_response"))
				{
					return ((string)(this.Results["msdyn_response"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
