#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_UnifiedRoutingQueueItemOperations")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_UnifiedRoutingQueueItemOperationsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string UnifiedRoutingQueueItemOperationsRequestParametersJson
		{
			get
			{
				if (this.Parameters.Contains("UnifiedRoutingQueueItemOperationsRequestParametersJson"))
				{
					return ((string)(this.Parameters["UnifiedRoutingQueueItemOperationsRequestParametersJson"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["UnifiedRoutingQueueItemOperationsRequestParametersJson"] = value;
			}
		}
		
		public msdyn_UnifiedRoutingQueueItemOperationsRequest()
		{
			this.RequestName = "msdyn_UnifiedRoutingQueueItemOperations";
			this.UnifiedRoutingQueueItemOperationsRequestParametersJson = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_UnifiedRoutingQueueItemOperations")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_UnifiedRoutingQueueItemOperationsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_UnifiedRoutingQueueItemOperationsResponse()
		{
		}
		
		public string UnifiedRoutingQueueItemOperationsResponsePropertiesJson
		{
			get
			{
				if (this.Results.Contains("UnifiedRoutingQueueItemOperationsResponsePropertiesJson"))
				{
					return ((string)(this.Results["UnifiedRoutingQueueItemOperationsResponsePropertiesJson"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
