#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_IoTGetModelStatusInternal")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_IoTGetModelStatusInternalRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string ScenarioId
		{
			get
			{
				if (this.Parameters.Contains("ScenarioId"))
				{
					return ((string)(this.Parameters["ScenarioId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ScenarioId"] = value;
			}
		}
		
		public msdyn_IoTGetModelStatusInternalRequest()
		{
			this.RequestName = "msdyn_IoTGetModelStatusInternal";
			this.ScenarioId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_IoTGetModelStatusInternal")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_IoTGetModelStatusInternalResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_IoTGetModelStatusInternalResponse()
		{
		}
		
		public string MLModelStatusJSON
		{
			get
			{
				if (this.Results.Contains("MLModelStatusJSON"))
				{
					return ((string)(this.Results["MLModelStatusJSON"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
