#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetPredictionModelStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetPredictionModelStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string PredictionName
		{
			get
			{
				if (this.Parameters.Contains("PredictionName"))
				{
					return ((string)(this.Parameters["PredictionName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PredictionName"] = value;
			}
		}
		
		public msdyn_GetPredictionModelStatusRequest()
		{
			this.RequestName = "msdyn_GetPredictionModelStatus";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetPredictionModelStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetPredictionModelStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetPredictionModelStatusResponse()
		{
		}
		
		public string PredictionModelStatus
		{
			get
			{
				if (this.Results.Contains("PredictionModelStatus"))
				{
					return ((string)(this.Results["PredictionModelStatus"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
