#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_UpdateAutoScheduledTrainingStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_UpdateAutoScheduledTrainingStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public bool AutoScheduledTraining
		{
			get
			{
				if (this.Parameters.Contains("AutoScheduledTraining"))
				{
					return ((bool)(this.Parameters["AutoScheduledTraining"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["AutoScheduledTraining"] = value;
			}
		}
		
		public string PredictionName
		{
			get
			{
				if (this.Parameters.Contains("PredictionName"))
				{
					return ((string)(this.Parameters["PredictionName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PredictionName"] = value;
			}
		}
		
		public string PredictionType
		{
			get
			{
				if (this.Parameters.Contains("PredictionType"))
				{
					return ((string)(this.Parameters["PredictionType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PredictionType"] = value;
			}
		}
		
		public msdyn_UpdateAutoScheduledTrainingStatusRequest()
		{
			this.RequestName = "msdyn_UpdateAutoScheduledTrainingStatus";
			this.AutoScheduledTraining = default(bool);
			this.PredictionName = default(string);
			this.PredictionType = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_UpdateAutoScheduledTrainingStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_UpdateAutoScheduledTrainingStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_UpdateAutoScheduledTrainingStatusResponse()
		{
		}
	}
}
#pragma warning restore CS1591
