#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SendMessageToOCService")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SendMessageToOCServiceRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string ServiceEndPoint
		{
			get
			{
				if (this.Parameters.Contains("ServiceEndPoint"))
				{
					return ((string)(this.Parameters["ServiceEndPoint"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ServiceEndPoint"] = value;
			}
		}
		
		public string RequestBody
		{
			get
			{
				if (this.Parameters.Contains("RequestBody"))
				{
					return ((string)(this.Parameters["RequestBody"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RequestBody"] = value;
			}
		}
		
		public msdyn_SendMessageToOCServiceRequest()
		{
			this.RequestName = "msdyn_SendMessageToOCService";
			this.ServiceEndPoint = default(string);
			this.RequestBody = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SendMessageToOCService")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SendMessageToOCServiceResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_SendMessageToOCServiceResponse()
		{
		}
		
		public string ResponseBody
		{
			get
			{
				if (this.Results.Contains("ResponseBody"))
				{
					return ((string)(this.Results["ResponseBody"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
