#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetHierarchyData")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetHierarchyDataRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string input
		{
			get
			{
				if (this.Parameters.Contains("input"))
				{
					return ((string)(this.Parameters["input"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["input"] = value;
			}
		}
		
		public msdyn_GetHierarchyDataRequest()
		{
			this.RequestName = "msdyn_GetHierarchyData";
			this.input = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetHierarchyData")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetHierarchyDataResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetHierarchyDataResponse()
		{
		}
		
		public string output
		{
			get
			{
				if (this.Results.Contains("output"))
				{
					return ((string)(this.Results["output"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
