#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_OSUpdateModelGrades")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_OSUpdateModelGradesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string PredictionGrade
		{
			get
			{
				if (this.Parameters.Contains("PredictionGrade"))
				{
					return ((string)(this.Parameters["PredictionGrade"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PredictionGrade"] = value;
			}
		}
		
		public msdyn_OSUpdateModelGradesRequest()
		{
			this.RequestName = "msdyn_OSUpdateModelGrades";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_OSUpdateModelGrades")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_OSUpdateModelGradesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_OSUpdateModelGradesResponse()
		{
		}
		
		public string GradeDefinition
		{
			get
			{
				if (this.Results.Contains("GradeDefinition"))
				{
					return ((string)(this.Results["GradeDefinition"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
