#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_IsSharePointEnabled")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_IsSharePointEnabledRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public msdyn_IsSharePointEnabledRequest()
		{
			this.RequestName = "msdyn_IsSharePointEnabled";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_IsSharePointEnabled")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_IsSharePointEnabledResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_IsSharePointEnabledResponse()
		{
		}
		
		public bool IsSharePointEnabled
		{
			get
			{
				if (this.Results.Contains("IsSharePointEnabled"))
				{
					return ((bool)(this.Results["IsSharePointEnabled"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
}
#pragma warning restore CS1591
