#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ForecastApi")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ForecastApiRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string WebApiName
		{
			get
			{
				if (this.Parameters.Contains("WebApiName"))
				{
					return ((string)(this.Parameters["WebApiName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["WebApiName"] = value;
			}
		}
		
		public string RequestJson
		{
			get
			{
				if (this.Parameters.Contains("RequestJson"))
				{
					return ((string)(this.Parameters["RequestJson"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RequestJson"] = value;
			}
		}
		
		public msdyn_ForecastApiRequest()
		{
			this.RequestName = "msdyn_ForecastApi";
			this.WebApiName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ForecastApi")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ForecastApiResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ForecastApiResponse()
		{
		}
		
		public string response
		{
			get
			{
				if (this.Results.Contains("response"))
				{
					return ((string)(this.Results["response"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
