#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ExecuteHttpServiceRequest")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ExecuteHttpServiceRequestRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_RequestUrl
		{
			get
			{
				if (this.Parameters.Contains("msdyn_RequestUrl"))
				{
					return ((string)(this.Parameters["msdyn_RequestUrl"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_RequestUrl"] = value;
			}
		}
		
		public int msdyn_CloudServiceApplicationType
		{
			get
			{
				if (this.Parameters.Contains("msdyn_CloudServiceApplicationType"))
				{
					return ((int)(this.Parameters["msdyn_CloudServiceApplicationType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["msdyn_CloudServiceApplicationType"] = value;
			}
		}
		
		public string msdyn_Method
		{
			get
			{
				if (this.Parameters.Contains("msdyn_Method"))
				{
					return ((string)(this.Parameters["msdyn_Method"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_Method"] = value;
			}
		}
		
		public string msdyn_RequestType
		{
			get
			{
				if (this.Parameters.Contains("msdyn_RequestType"))
				{
					return ((string)(this.Parameters["msdyn_RequestType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_RequestType"] = value;
			}
		}
		
		public string msdyn_RequestBody
		{
			get
			{
				if (this.Parameters.Contains("msdyn_RequestBody"))
				{
					return ((string)(this.Parameters["msdyn_RequestBody"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_RequestBody"] = value;
			}
		}
		
		public msdyn_ExecuteHttpServiceRequestRequest()
		{
			this.RequestName = "msdyn_ExecuteHttpServiceRequest";
			this.msdyn_RequestUrl = default(string);
			this.msdyn_CloudServiceApplicationType = default(int);
			this.msdyn_Method = default(string);
			this.msdyn_RequestType = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ExecuteHttpServiceRequest")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ExecuteHttpServiceRequestResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ExecuteHttpServiceRequestResponse()
		{
		}
		
		public string msdyn_Response
		{
			get
			{
				if (this.Results.Contains("msdyn_Response"))
				{
					return ((string)(this.Results["msdyn_Response"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string msdyn_StatusCode
		{
			get
			{
				if (this.Results.Contains("msdyn_StatusCode"))
				{
					return ((string)(this.Results["msdyn_StatusCode"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
