#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_FilterInActiveNBACards")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_FilterInActiveNBACardsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_NBAEntityIds
		{
			get
			{
				if (this.Parameters.Contains("msdyn_NBAEntityIds"))
				{
					return ((string)(this.Parameters["msdyn_NBAEntityIds"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_NBAEntityIds"] = value;
			}
		}
		
		public msdyn_FilterInActiveNBACardsRequest()
		{
			this.RequestName = "msdyn_FilterInActiveNBACards";
			this.msdyn_NBAEntityIds = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_FilterInActiveNBACards")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_FilterInActiveNBACardsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_FilterInActiveNBACardsResponse()
		{
		}
		
		public string msdyn_ActiveNBAEntityIds
		{
			get
			{
				if (this.Results.Contains("msdyn_ActiveNBAEntityIds"))
				{
					return ((string)(this.Results["msdyn_ActiveNBAEntityIds"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
