#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_IoTGetIoTAlertCustomAttributes")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_IoTGetIoTAlertCustomAttributesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public msdyn_IoTGetIoTAlertCustomAttributesRequest()
		{
			this.RequestName = "msdyn_IoTGetIoTAlertCustomAttributes";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_IoTGetIoTAlertCustomAttributes")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_IoTGetIoTAlertCustomAttributesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_IoTGetIoTAlertCustomAttributesResponse()
		{
		}
		
		public string Metadata
		{
			get
			{
				if (this.Results.Contains("Metadata"))
				{
					return ((string)(this.Results["Metadata"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
