#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_DeletePrediction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_DeletePredictionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string ModelId
		{
			get
			{
				if (this.Parameters.Contains("ModelId"))
				{
					return ((string)(this.Parameters["ModelId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ModelId"] = value;
			}
		}
		
		public bool IsCrmDeleteOnly
		{
			get
			{
				if (this.Parameters.Contains("IsCrmDeleteOnly"))
				{
					return ((bool)(this.Parameters["IsCrmDeleteOnly"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["IsCrmDeleteOnly"] = value;
			}
		}
		
		public string PredictionName
		{
			get
			{
				if (this.Parameters.Contains("PredictionName"))
				{
					return ((string)(this.Parameters["PredictionName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PredictionName"] = value;
			}
		}
		
		public bool IsActiveModel
		{
			get
			{
				if (this.Parameters.Contains("IsActiveModel"))
				{
					return ((bool)(this.Parameters["IsActiveModel"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["IsActiveModel"] = value;
			}
		}
		
		public msdyn_DeletePredictionRequest()
		{
			this.RequestName = "msdyn_DeletePrediction";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_DeletePrediction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_DeletePredictionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_DeletePredictionResponse()
		{
		}
	}
}
#pragma warning restore CS1591
