#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ExternalContextCommitTranscriptUpload")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ExternalContextCommitTranscriptUploadRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public string FileContinuationToken
		{
			get
			{
				if (this.Parameters.Contains("FileContinuationToken"))
				{
					return ((string)(this.Parameters["FileContinuationToken"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["FileContinuationToken"] = value;
			}
		}
		
		public string[] BlockList
		{
			get
			{
				if (this.Parameters.Contains("BlockList"))
				{
					return ((string[])(this.Parameters["BlockList"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["BlockList"] = value;
			}
		}
		
		public msdyn_ExternalContextCommitTranscriptUploadRequest()
		{
			this.RequestName = "msdyn_ExternalContextCommitTranscriptUpload";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
			this.FileContinuationToken = default(string);
			this.BlockList = default(string[]);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ExternalContextCommitTranscriptUpload")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ExternalContextCommitTranscriptUploadResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ExternalContextCommitTranscriptUploadResponse()
		{
		}
		
		public System.Guid FileId
		{
			get
			{
				if (this.Results.Contains("FileId"))
				{
					return ((System.Guid)(this.Results["FileId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
		}
	}
}
#pragma warning restore CS1591
