#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_getinboundurl")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_getinboundurlRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public System.Guid channeldefinitionid
		{
			get
			{
				if (this.Parameters.Contains("channeldefinitionid"))
				{
					return ((System.Guid)(this.Parameters["channeldefinitionid"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["channeldefinitionid"] = value;
			}
		}
		
		public string contactpoint
		{
			get
			{
				if (this.Parameters.Contains("contactpoint"))
				{
					return ((string)(this.Parameters["contactpoint"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["contactpoint"] = value;
			}
		}
		
		public msdyn_getinboundurlRequest()
		{
			this.RequestName = "msdyn_getinboundurl";
			this.channeldefinitionid = default(System.Guid);
			this.contactpoint = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_getinboundurl")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_getinboundurlResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_getinboundurlResponse()
		{
		}
		
		public string inboundurl
		{
			get
			{
				if (this.Results.Contains("inboundurl"))
				{
					return ((string)(this.Results["inboundurl"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string[] scopes
		{
			get
			{
				if (this.Results.Contains("scopes"))
				{
					return ((string[])(this.Results["scopes"]));
				}
				else
				{
					return default(string[]);
				}
			}
		}
		
		public string tenant
		{
			get
			{
				if (this.Results.Contains("tenant"))
				{
					return ((string)(this.Results["tenant"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
