#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SetSharePointDocumentStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SetSharePointDocumentStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public bool Enable
		{
			get
			{
				if (this.Parameters.Contains("Enable"))
				{
					return ((bool)(this.Parameters["Enable"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["Enable"] = value;
			}
		}
		
		public string LogicalEntityNames
		{
			get
			{
				if (this.Parameters.Contains("LogicalEntityNames"))
				{
					return ((string)(this.Parameters["LogicalEntityNames"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["LogicalEntityNames"] = value;
			}
		}
		
		public msdyn_SetSharePointDocumentStatusRequest()
		{
			this.RequestName = "msdyn_SetSharePointDocumentStatus";
			this.Enable = default(bool);
			this.LogicalEntityNames = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SetSharePointDocumentStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_SetSharePointDocumentStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_SetSharePointDocumentStatusResponse()
		{
		}
		
		public string FailedLogicalEntityNames
		{
			get
			{
				if (this.Results.Contains("FailedLogicalEntityNames"))
				{
					return ((string)(this.Results["FailedLogicalEntityNames"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public bool OperationResult
		{
			get
			{
				if (this.Results.Contains("OperationResult"))
				{
					return ((bool)(this.Results["OperationResult"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
		
		public string PassedLogicalEntityNames
		{
			get
			{
				if (this.Results.Contains("PassedLogicalEntityNames"))
				{
					return ((string)(this.Results["PassedLogicalEntityNames"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
