#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_updatesequencetargetstepdata")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_updatesequencetargetstepdataRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_sequencetargetstepid
		{
			get
			{
				if (this.Parameters.Contains("msdyn_sequencetargetstepid"))
				{
					return ((string)(this.Parameters["msdyn_sequencetargetstepid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_sequencetargetstepid"] = value;
			}
		}
		
		public string msdyn_linkedactivityid
		{
			get
			{
				if (this.Parameters.Contains("msdyn_linkedactivityid"))
				{
					return ((string)(this.Parameters["msdyn_linkedactivityid"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_linkedactivityid"] = value;
			}
		}
		
		public msdyn_updatesequencetargetstepdataRequest()
		{
			this.RequestName = "msdyn_updatesequencetargetstepdata";
			this.msdyn_sequencetargetstepid = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_updatesequencetargetstepdata")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_updatesequencetargetstepdataResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_updatesequencetargetstepdataResponse()
		{
		}
	}
}
#pragma warning restore CS1591
