#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetFeatureConsentStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetFeatureConsentStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string payload
		{
			get
			{
				if (this.Parameters.Contains("payload"))
				{
					return ((string)(this.Parameters["payload"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["payload"] = value;
			}
		}
		
		public msdyn_GetFeatureConsentStatusRequest()
		{
			this.RequestName = "msdyn_GetFeatureConsentStatus";
			this.payload = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetFeatureConsentStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetFeatureConsentStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetFeatureConsentStatusResponse()
		{
		}
	}
}
#pragma warning restore CS1591
