#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetIoTVisualizationSummary")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetIoTVisualizationSummaryRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string DeviceId
		{
			get
			{
				if (this.Parameters.Contains("DeviceId"))
				{
					return ((string)(this.Parameters["DeviceId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["DeviceId"] = value;
			}
		}
		
		public string ConfigurationTypeId
		{
			get
			{
				if (this.Parameters.Contains("ConfigurationTypeId"))
				{
					return ((string)(this.Parameters["ConfigurationTypeId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ConfigurationTypeId"] = value;
			}
		}
		
		public msdyn_GetIoTVisualizationSummaryRequest()
		{
			this.RequestName = "msdyn_GetIoTVisualizationSummary";
			this.DeviceId = default(string);
			this.ConfigurationTypeId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetIoTVisualizationSummary")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetIoTVisualizationSummaryResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetIoTVisualizationSummaryResponse()
		{
		}
		
		public string SummaryOutput
		{
			get
			{
				if (this.Results.Contains("SummaryOutput"))
				{
					return ((string)(this.Results["SummaryOutput"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
