#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetFCBValue")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetFCBValueRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string FCBName
		{
			get
			{
				if (this.Parameters.Contains("FCBName"))
				{
					return ((string)(this.Parameters["FCBName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["FCBName"] = value;
			}
		}
		
		public msdyn_GetFCBValueRequest()
		{
			this.RequestName = "msdyn_GetFCBValue";
			this.FCBName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetFCBValue")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetFCBValueResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetFCBValueResponse()
		{
		}
		
		public bool FCBValue
		{
			get
			{
				if (this.Results.Contains("FCBValue"))
				{
					return ((bool)(this.Results["FCBValue"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
}
#pragma warning restore CS1591
