#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_recurringsegmentaction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_recurringsegmentactionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string payload
		{
			get
			{
				if (this.Parameters.Contains("payload"))
				{
					return ((string)(this.Parameters["payload"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["payload"] = value;
			}
		}
		
		public string operationType
		{
			get
			{
				if (this.Parameters.Contains("operationType"))
				{
					return ((string)(this.Parameters["operationType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["operationType"] = value;
			}
		}
		
		public string segmentId
		{
			get
			{
				if (this.Parameters.Contains("segmentId"))
				{
					return ((string)(this.Parameters["segmentId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["segmentId"] = value;
			}
		}
		
		public msdyn_recurringsegmentactionRequest()
		{
			this.RequestName = "msdyn_recurringsegmentaction";
			this.payload = default(string);
			this.operationType = default(string);
			this.segmentId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_recurringsegmentaction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_recurringsegmentactionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_recurringsegmentactionResponse()
		{
		}
		
		public string result
		{
			get
			{
				if (this.Results.Contains("result"))
				{
					return ((string)(this.Results["result"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
