#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ForecastRecalculateAsync")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ForecastRecalculateAsyncRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference ForecastInstance
		{
			get
			{
				if (this.Parameters.Contains("ForecastInstance"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["ForecastInstance"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["ForecastInstance"] = value;
			}
		}
		
		public bool IsRefreshHierarchy
		{
			get
			{
				if (this.Parameters.Contains("IsRefreshHierarchy"))
				{
					return ((bool)(this.Parameters["IsRefreshHierarchy"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["IsRefreshHierarchy"] = value;
			}
		}
		
		public msdyn_ForecastRecalculateAsyncRequest()
		{
			this.RequestName = "msdyn_ForecastRecalculateAsync";
			this.ForecastInstance = default(Microsoft.Xrm.Sdk.EntityReference);
			this.IsRefreshHierarchy = default(bool);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ForecastRecalculateAsync")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ForecastRecalculateAsyncResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ForecastRecalculateAsyncResponse()
		{
		}
	}
}
#pragma warning restore CS1591
