#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_StartODOSDeprovisioning")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_StartODOSDeprovisioningRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string FeatureName
		{
			get
			{
				if (this.Parameters.Contains("FeatureName"))
				{
					return ((string)(this.Parameters["FeatureName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["FeatureName"] = value;
			}
		}
		
		public bool IsDeprecationDeprovisioning
		{
			get
			{
				if (this.Parameters.Contains("IsDeprecationDeprovisioning"))
				{
					return ((bool)(this.Parameters["IsDeprecationDeprovisioning"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["IsDeprecationDeprovisioning"] = value;
			}
		}
		
		public msdyn_StartODOSDeprovisioningRequest()
		{
			this.RequestName = "msdyn_StartODOSDeprovisioning";
			this.FeatureName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_StartODOSDeprovisioning")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_StartODOSDeprovisioningResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_StartODOSDeprovisioningResponse()
		{
		}
	}
}
#pragma warning restore CS1591
