#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetTimeLineRecords")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetTimeLineRecordsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string RegardingObjectId
		{
			get
			{
				if (this.Parameters.Contains("RegardingObjectId"))
				{
					return ((string)(this.Parameters["RegardingObjectId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RegardingObjectId"] = value;
			}
		}
		
		public string NumberOfRecords
		{
			get
			{
				if (this.Parameters.Contains("NumberOfRecords"))
				{
					return ((string)(this.Parameters["NumberOfRecords"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["NumberOfRecords"] = value;
			}
		}
		
		public msdyn_GetTimeLineRecordsRequest()
		{
			this.RequestName = "msdyn_GetTimeLineRecords";
			this.RegardingObjectId = default(string);
			this.NumberOfRecords = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetTimeLineRecords")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_GetTimeLineRecordsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetTimeLineRecordsResponse()
		{
		}
		
		public string TimeLineWallRecords
		{
			get
			{
				if (this.Results.Contains("TimeLineWallRecords"))
				{
					return ((string)(this.Results["TimeLineWallRecords"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
