#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_WKWGDPRDeleteStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_WKWGDPRDeleteStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string[] UserIds
		{
			get
			{
				if (this.Parameters.Contains("UserIds"))
				{
					return ((string[])(this.Parameters["UserIds"]));
				}
				else
				{
					return default(string[]);
				}
			}
			set
			{
				this.Parameters["UserIds"] = value;
			}
		}
		
		public msdyn_WKWGDPRDeleteStatusRequest()
		{
			this.RequestName = "msdyn_WKWGDPRDeleteStatus";
			this.UserIds = default(string[]);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_WKWGDPRDeleteStatus")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_WKWGDPRDeleteStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_WKWGDPRDeleteStatusResponse()
		{
		}
		
		public string Response
		{
			get
			{
				if (this.Results.Contains("Response"))
				{
					return ((string)(this.Results["Response"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
