#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ActionCardCreate")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ActionCardCreateRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string actionCardCreateParams
		{
			get
			{
				if (this.Parameters.Contains("actionCardCreateParams"))
				{
					return ((string)(this.Parameters["actionCardCreateParams"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["actionCardCreateParams"] = value;
			}
		}
		
		public msdyn_ActionCardCreateRequest()
		{
			this.RequestName = "msdyn_ActionCardCreate";
			this.actionCardCreateParams = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ActionCardCreate")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ActionCardCreateResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ActionCardCreateResponse()
		{
		}
	}
}
#pragma warning restore CS1591
