#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ShowPrivacyTerms")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ShowPrivacyTermsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public int StreamSource
		{
			get
			{
				if (this.Parameters.Contains("StreamSource"))
				{
					return ((int)(this.Parameters["StreamSource"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["StreamSource"] = value;
			}
		}
		
		public msdyn_ShowPrivacyTermsRequest()
		{
			this.RequestName = "msdyn_ShowPrivacyTerms";
			this.StreamSource = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ShowPrivacyTerms")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ShowPrivacyTermsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ShowPrivacyTermsResponse()
		{
		}
		
		public bool ShowPrivacyTerms
		{
			get
			{
				if (this.Results.Contains("ShowPrivacyTerms"))
				{
					return ((bool)(this.Results["ShowPrivacyTerms"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
}
#pragma warning restore CS1591
