#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_JsonGetString")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_JsonGetStringRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string Json
		{
			get
			{
				if (this.Parameters.Contains("Json"))
				{
					return ((string)(this.Parameters["Json"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Json"] = value;
			}
		}
		
		public string PropertyPath
		{
			get
			{
				if (this.Parameters.Contains("PropertyPath"))
				{
					return ((string)(this.Parameters["PropertyPath"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PropertyPath"] = value;
			}
		}
		
		public string DefaultReturnValue
		{
			get
			{
				if (this.Parameters.Contains("DefaultReturnValue"))
				{
					return ((string)(this.Parameters["DefaultReturnValue"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["DefaultReturnValue"] = value;
			}
		}
		
		public msdyn_JsonGetStringRequest()
		{
			this.RequestName = "msdyn_JsonGetString";
			this.PropertyPath = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_JsonGetString")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_JsonGetStringResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_JsonGetStringResponse()
		{
		}
		
		public string Value
		{
			get
			{
				if (this.Results.Contains("Value"))
				{
					return ((string)(this.Results["Value"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
