#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ProductDeterminationProvisioningAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ProductDeterminationProvisioningActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string RequestPayload
		{
			get
			{
				if (this.Parameters.Contains("RequestPayload"))
				{
					return ((string)(this.Parameters["RequestPayload"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RequestPayload"] = value;
			}
		}
		
		public msdyn_ProductDeterminationProvisioningActionRequest()
		{
			this.RequestName = "msdyn_ProductDeterminationProvisioningAction";
			this.RequestPayload = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ProductDeterminationProvisioningAction")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ProductDeterminationProvisioningActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ProductDeterminationProvisioningActionResponse()
		{
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
