#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_ActivateWorkflow")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ActivateWorkflowRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string msdyn_WorkflowUniqueName
		{
			get
			{
				if (this.Parameters.Contains("msdyn_WorkflowUniqueName"))
				{
					return ((string)(this.Parameters["msdyn_WorkflowUniqueName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_WorkflowUniqueName"] = value;
			}
		}
		
		public string msdyn_WorkflowId
		{
			get
			{
				if (this.Parameters.Contains("msdyn_WorkflowId"))
				{
					return ((string)(this.Parameters["msdyn_WorkflowId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["msdyn_WorkflowId"] = value;
			}
		}
		
		public msdyn_ActivateWorkflowRequest()
		{
			this.RequestName = "msdyn_ActivateWorkflow";
			this.msdyn_WorkflowId = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_ActivateWorkflow")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class msdyn_ActivateWorkflowResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_ActivateWorkflowResponse()
		{
		}
		
		public string msdyn_ActivateWorkflowResponse
		{
			get
			{
				if (this.Results.Contains("msdyn_ActivateWorkflowResponse"))
				{
					return ((string)(this.Results["msdyn_ActivateWorkflowResponse"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
