#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("pm_RefreshProcessMiningLicensingCapacity")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class pm_RefreshProcessMiningLicensingCapacityRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public pm_RefreshProcessMiningLicensingCapacityRequest()
		{
			this.RequestName = "pm_RefreshProcessMiningLicensingCapacity";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("pm_RefreshProcessMiningLicensingCapacity")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class pm_RefreshProcessMiningLicensingCapacityResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public pm_RefreshProcessMiningLicensingCapacityResponse()
		{
		}
		
		public string response
		{
			get
			{
				if (this.Results.Contains("response"))
				{
					return ((string)(this.Results["response"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
