#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("QueryZendeskUnstructuredArticles")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class QueryZendeskUnstructuredArticlesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string filterCriteria
		{
			get
			{
				if (this.Parameters.Contains("filterCriteria"))
				{
					return ((string)(this.Parameters["filterCriteria"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["filterCriteria"] = value;
			}
		}
		
		public string connectionId
		{
			get
			{
				if (this.Parameters.Contains("connectionId"))
				{
					return ((string)(this.Parameters["connectionId"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["connectionId"] = value;
			}
		}
		
		public int searchResultCount
		{
			get
			{
				if (this.Parameters.Contains("searchResultCount"))
				{
					return ((int)(this.Parameters["searchResultCount"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["searchResultCount"] = value;
			}
		}
		
		public string userQueryText
		{
			get
			{
				if (this.Parameters.Contains("userQueryText"))
				{
					return ((string)(this.Parameters["userQueryText"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["userQueryText"] = value;
			}
		}
		
		public QueryZendeskUnstructuredArticlesRequest()
		{
			this.RequestName = "QueryZendeskUnstructuredArticles";
			this.connectionId = default(string);
			this.userQueryText = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("QueryZendeskUnstructuredArticles")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class QueryZendeskUnstructuredArticlesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public QueryZendeskUnstructuredArticlesResponse()
		{
		}
		
		public string knowledgePluginResponse
		{
			get
			{
				if (this.Results.Contains("knowledgePluginResponse"))
				{
					return ((string)(this.Results["knowledgePluginResponse"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
#pragma warning restore CS1591
