#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseEntities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("RemoveCertificateCredential")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class RemoveCertificateCredentialRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string entityLogicalName
		{
			get
			{
				if (this.Parameters.Contains("entityLogicalName"))
				{
					return ((string)(this.Parameters["entityLogicalName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["entityLogicalName"] = value;
			}
		}
		
		public System.Guid entityId
		{
			get
			{
				if (this.Parameters.Contains("entityId"))
				{
					return ((System.Guid)(this.Parameters["entityId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["entityId"] = value;
			}
		}
		
		public System.Guid certificateCredentialId
		{
			get
			{
				if (this.Parameters.Contains("certificateCredentialId"))
				{
					return ((System.Guid)(this.Parameters["certificateCredentialId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["certificateCredentialId"] = value;
			}
		}
		
		public RemoveCertificateCredentialRequest()
		{
			this.RequestName = "RemoveCertificateCredential";
			this.entityLogicalName = default(string);
			this.entityId = default(System.Guid);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("RemoveCertificateCredential")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.6")]
	public partial class RemoveCertificateCredentialResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public RemoveCertificateCredentialResponse()
		{
		}
	}
}
#pragma warning restore CS1591
